/*
 * This file was automatically generated by EvoSuite
 */

package org.exolab.jms.net.multiplexer;

import org.junit.Test;
import org.junit.runner.RunWith;
import org.evosuite.junit.EvoSuiteRunner;
import static org.junit.Assert.*;
import java.io.DataInputStream;
import java.io.DataOutputStream;
import java.io.IOException;
import java.io.InputStream;
import java.io.OutputStream;
import java.io.PipedInputStream;
import java.io.PipedOutputStream;
import java.security.Principal;
import javax.management.remote.JMXPrincipal;
import org.exolab.jms.common.security.BasicPrincipal;
import org.exolab.jms.net.connector.Authenticator;
import org.exolab.jms.net.connector.ResourceException;
import org.exolab.jms.net.connector.SecurityException;
import org.exolab.jms.net.multiplexer.Channel;
import org.exolab.jms.net.multiplexer.Endpoint;
import org.exolab.jms.net.multiplexer.Multiplexer;
import org.exolab.jms.net.multiplexer.MultiplexerListener;
import org.junit.BeforeClass;

@RunWith(EvoSuiteRunner.class)
public class TestMultiplexer {

  @BeforeClass 
  public static void initEvoSuiteFramework(){ 
    org.evosuite.Properties.REPLACE_CALLS = true; 
  } 


  @Test
  public void test0()  throws Throwable  {
      Multiplexer multiplexer0 = new Multiplexer();
      multiplexer0.isClosed();
      assertEquals(false, multiplexer0.isClient());
  }

  @Test
  public void test1()  throws Throwable  {
      Multiplexer multiplexer0 = new Multiplexer();
      multiplexer0.getPrincipal();
      assertEquals(false, multiplexer0.isClient());
  }

  @Test
  public void test2()  throws Throwable  {
      Multiplexer multiplexer0 = new Multiplexer();
      byte[] byteArray0 = new byte[9];
      // Undeclared exception!
      try {
        multiplexer0.send((byte)0, (int) (byte)0, byteArray0, (int) (byte) (-41), (int) (byte)0);
        fail("Expecting exception: NullPointerException");
      } catch(NullPointerException e) {
      }
  }

  @Test
  public void test3()  throws Throwable  {
      Multiplexer multiplexer0 = new Multiplexer();
      // Undeclared exception!
      try {
        multiplexer0.close((Channel) null);
        fail("Expecting exception: NullPointerException");
      } catch(NullPointerException e) {
      }
  }

  @Test
  public void test4()  throws Throwable  {
      BasicPrincipal basicPrincipal0 = new BasicPrincipal(")`]pvJ-:4", ")`]pvJ-:4");
      Multiplexer multiplexer0 = null;
      try {
        multiplexer0 = new Multiplexer((MultiplexerListener) null, (Endpoint) null, (Principal) basicPrincipal0);
        fail("Expecting exception: IllegalArgumentException");
      } catch(IllegalArgumentException e) {
        /*
         * Argument 'listener' is null
         */
      }
  }

  @Test
  public void test5()  throws Throwable  {
      Multiplexer multiplexer0 = new Multiplexer();
      boolean boolean0 = multiplexer0.isClient();
      assertEquals(false, boolean0);
  }

  @Test
  public void test6()  throws Throwable  {
      Multiplexer multiplexer0 = null;
      try {
        multiplexer0 = new Multiplexer((MultiplexerListener) null, (Endpoint) null, (Authenticator) null);
        fail("Expecting exception: IllegalArgumentException");
      } catch(IllegalArgumentException e) {
        /*
         * Argument 'listener' is null
         */
      }
  }

  @Test
  public void test7()  throws Throwable  {
      Multiplexer multiplexer0 = new Multiplexer();
      multiplexer0.release((Channel) null);
      assertEquals(false, multiplexer0.isClient());
  }

  @Test
  public void test8()  throws Throwable  {
      Multiplexer multiplexer0 = new Multiplexer();
      // Undeclared exception!
      try {
        multiplexer0.run();
        fail("Expecting exception: NullPointerException");
      } catch(NullPointerException e) {
      }
  }

  @Test
  public void test9()  throws Throwable  {
      Multiplexer multiplexer0 = new Multiplexer();
      // Undeclared exception!
      try {
        multiplexer0.close();
        fail("Expecting exception: NullPointerException");
      } catch(NullPointerException e) {
      }
  }

  @Test
  public void test10()  throws Throwable  {
      Multiplexer multiplexer0 = new Multiplexer();
      PipedInputStream pipedInputStream0 = new PipedInputStream();
      PipedOutputStream pipedOutputStream0 = new PipedOutputStream(pipedInputStream0);
      DataOutputStream dataOutputStream0 = new DataOutputStream((OutputStream) pipedOutputStream0);
      DataInputStream dataInputStream0 = new DataInputStream((InputStream) pipedInputStream0);
      multiplexer0.handshake(dataOutputStream0, dataInputStream0);
  }

  @Test
  public void test11()  throws Throwable  {
      Multiplexer multiplexer0 = new Multiplexer();
      // Undeclared exception!
      try {
        multiplexer0.authenticate((Principal) null);
        fail("Expecting exception: NullPointerException");
      } catch(NullPointerException e) {
      }
  }

  @Test
  public void test12()  throws Throwable  {
      Multiplexer multiplexer0 = new Multiplexer();
      BasicPrincipal basicPrincipal0 = new BasicPrincipal("0|,C/`p5<C,0#", "0|,C/`p5<C,0#");
      // Undeclared exception!
      try {
        multiplexer0.authenticate((Principal) basicPrincipal0);
        fail("Expecting exception: NullPointerException");
      } catch(NullPointerException e) {
      }
  }

  @Test
  public void test13()  throws Throwable  {
      Multiplexer multiplexer0 = new Multiplexer();
      JMXPrincipal jMXPrincipal0 = new JMXPrincipal("");
      // Undeclared exception!
      try {
        multiplexer0.authenticate((Principal) jMXPrincipal0);
        fail("Expecting exception: NullPointerException");
      } catch(NullPointerException e) {
      }
  }
}
