/*
 * This file was automatically generated by EvoSuite
 */

package org.exolab.jms.net.invoke;

import org.junit.Test;
import org.junit.runner.RunWith;
import org.evosuite.junit.EvoSuiteRunner;
import static org.junit.Assert.*;
import java.rmi.RemoteException;
import java.rmi.server.ExportException;
import org.exolab.jms.client.net.SharedORB;
import org.exolab.jms.net.invoke.ExportServiceImpl;
import org.exolab.jms.net.orb.ORB;
import org.junit.BeforeClass;

@RunWith(EvoSuiteRunner.class)
public class TestExportServiceImpl {

  @BeforeClass 
  public static void initEvoSuiteFramework(){ 
    org.evosuite.Properties.REPLACE_CALLS = true; 
  } 


  @Test
  public void test0()  throws Throwable  {
      SharedORB sharedORB0 = (SharedORB)SharedORB.getInstance();
      ExportServiceImpl exportServiceImpl0 = new ExportServiceImpl((Object) null, (ORB) sharedORB0);
      try {
        exportServiceImpl0.exportObjectTo();
        fail("Expecting exception: ExportException");
      } catch(ExportException e) {
        /*
         * Cannot export - no current caller
         */
      }
  }
}
