/*
 * This file was automatically generated by EvoSuite
 */

package org.exolab.jms.net.invoke;

import org.junit.Test;
import org.junit.runner.RunWith;
import org.evosuite.junit.EvoSuiteRunner;
import static org.junit.Assert.*;
import java.rmi.server.ObjID;
import org.exolab.jms.net.invoke.LoggingCallback__Proxy;
import org.exolab.jms.net.orb.UnicastDelegate;
import org.exolab.jms.net.proxy.Delegate;
import org.exolab.jms.net.proxy.RemoteInvocationException;
import org.junit.BeforeClass;

@RunWith(EvoSuiteRunner.class)
public class TestLoggingCallback__Proxy {

  @BeforeClass 
  public static void initEvoSuiteFramework(){ 
    org.evosuite.Properties.REPLACE_CALLS = true; 
  } 


  @Test
  public void test0()  throws Throwable  {
      ObjID objID0 = new ObjID((-1));
      UnicastDelegate unicastDelegate0 = new UnicastDelegate(objID0, "");
      LoggingCallback__Proxy loggingCallback__Proxy0 = new LoggingCallback__Proxy((Delegate) unicastDelegate0);
      // Undeclared exception!
      try {
        loggingCallback__Proxy0.invoke((Object) "");
        fail("Expecting exception: RemoteInvocationException");
      } catch(RemoteInvocationException e) {
      }
  }
}
