/*
 * This file was automatically generated by EvoSuite
 */

package org.exolab.jms.selector;

import org.junit.Test;
import org.junit.runner.RunWith;
import org.evosuite.junit.EvoSuiteRunner;
import static org.junit.Assert.*;
import java.util.HashSet;
import org.exolab.jms.selector.Identifier;
import org.exolab.jms.selector.InExpression;
import org.junit.BeforeClass;

@RunWith(EvoSuiteRunner.class)
public class TestInExpression {

  @BeforeClass 
  public static void initEvoSuiteFramework(){ 
    org.evosuite.Properties.REPLACE_CALLS = true; 
  } 


  @Test
  public void test0()  throws Throwable  {
      HashSet<String> hashSet0 = new HashSet<String>();
      InExpression inExpression0 = new InExpression((Identifier) null, (HashSet) hashSet0);
      assertNotNull(inExpression0);
  }
}
