/*
 * This file was automatically generated by EvoSuite
 */

package org.exolab.jms.net.orb;

import org.junit.Test;
import org.junit.runner.RunWith;
import org.evosuite.junit.EvoSuiteRunner;
import static org.junit.Assert.*;
import java.lang.reflect.Method;
import java.rmi.server.ObjID;
import org.exolab.jms.net.connector.Connection;
import org.exolab.jms.net.orb.UnicastDelegate;
import org.exolab.jms.net.uri.InvalidURIException;
import org.junit.BeforeClass;

@RunWith(EvoSuiteRunner.class)
public class TestUnicastDelegate {

  @BeforeClass 
  public static void initEvoSuiteFramework(){ 
    org.evosuite.Properties.REPLACE_CALLS = true; 
  } 


  @Test
  public void test0()  throws Throwable  {
      ObjID objID0 = new ObjID((-1419));
      UnicastDelegate unicastDelegate0 = new UnicastDelegate(objID0, "");
      unicastDelegate0.dispose();
  }

  @Test
  public void test1()  throws Throwable  {
      UnicastDelegate unicastDelegate0 = new UnicastDelegate((ObjID) null, (Connection) null);
      assertNotNull(unicastDelegate0);
  }

  @Test
  public void test2()  throws Throwable  {
      UnicastDelegate unicastDelegate0 = new UnicastDelegate();
      assertNotNull(unicastDelegate0);
  }

  @Test
  public void test3()  throws Throwable  {
      ObjID objID0 = new ObjID((-1419));
      UnicastDelegate unicastDelegate0 = new UnicastDelegate(objID0, "");
      Object[] objectArray0 = new Object[14];
      try {
        unicastDelegate0.invoke((Method) null, objectArray0, (long) (-1419));
        fail("Expecting exception: InvalidURIException");
      } catch(InvalidURIException e) {
        /*
         * Argument base is null and argument uriSpec is null or an empty string
         */
      }
  }
}
