/*
 * This file was automatically generated by EvoSuite
 */

package org.exolab.jms.net.orb;

import org.junit.Test;
import org.junit.runner.RunWith;
import org.evosuite.junit.EvoSuiteRunner;
import static org.junit.Assert.*;
import java.rmi.AccessException;
import java.rmi.AlreadyBoundException;
import java.rmi.NotBoundException;
import java.rmi.RemoteException;
import java.rmi.server.ObjID;
import org.exolab.jms.net.orb.RegistryImpl__Proxy;
import org.exolab.jms.net.orb.UnicastDelegate;
import org.exolab.jms.net.proxy.Delegate;
import org.exolab.jms.net.proxy.Proxy;
import org.exolab.jms.net.uri.InvalidURIException;
import org.junit.BeforeClass;

@RunWith(EvoSuiteRunner.class)
public class TestRegistryImpl__Proxy {

  @BeforeClass 
  public static void initEvoSuiteFramework(){ 
    org.evosuite.Properties.REPLACE_CALLS = true; 
  } 


  @Test
  public void test0()  throws Throwable  {
      ObjID objID0 = new ObjID();
      UnicastDelegate unicastDelegate0 = new UnicastDelegate(objID0, "");
      RegistryImpl__Proxy registryImpl__Proxy0 = new RegistryImpl__Proxy((Delegate) unicastDelegate0);
      try {
        registryImpl__Proxy0.lookup((String) null);
        fail("Expecting exception: InvalidURIException");
      } catch(InvalidURIException e) {
        /*
         * Argument base is null and argument uriSpec is null or an empty string
         */
      }
  }

  @Test
  public void test1()  throws Throwable  {
      ObjID objID0 = new ObjID();
      UnicastDelegate unicastDelegate0 = new UnicastDelegate(objID0, "I.@:8dGF@53yjh3CH");
      RegistryImpl__Proxy registryImpl__Proxy0 = new RegistryImpl__Proxy((Delegate) unicastDelegate0);
      try {
        registryImpl__Proxy0.unbind("I.@:8dGF@53yjh3CH");
        fail("Expecting exception: InvalidURIException");
      } catch(InvalidURIException e) {
        /*
         * The scheme is not conformant.
         */
      }
  }

  @Test
  public void test2()  throws Throwable  {
      ObjID objID0 = new ObjID();
      UnicastDelegate unicastDelegate0 = new UnicastDelegate(objID0, "h+/");
      RegistryImpl__Proxy registryImpl__Proxy0 = new RegistryImpl__Proxy((Delegate) unicastDelegate0);
      try {
        registryImpl__Proxy0.bind("h+/", (Proxy) registryImpl__Proxy0);
        fail("Expecting exception: InvalidURIException");
      } catch(InvalidURIException e) {
        /*
         * No scheme found in URI.
         */
      }
  }
}
