/*
 * This file was automatically generated by EvoSuite
 */

package org.exolab.jms.net.orb;

import org.junit.Test;
import org.junit.runner.RunWith;
import org.evosuite.junit.EvoSuiteRunner;
import static org.junit.Assert.*;
import java.io.InputStream;
import java.rmi.NoSuchObjectException;
import java.rmi.server.ObjID;
import org.exolab.jms.net.Callback;
import org.exolab.jms.net.orb.ObjectRef;
import org.exolab.jms.net.uri.URI;
import org.junit.BeforeClass;

@RunWith(EvoSuiteRunner.class)
public class TestObjectRef {

  @BeforeClass 
  public static void initEvoSuiteFramework(){ 
    org.evosuite.Properties.REPLACE_CALLS = true; 
  } 


  @Test
  public void test0()  throws Throwable  {
      Class<?> class0 = ObjID.class;
      ObjectRef objectRef0 = new ObjectRef((ObjID) null, (Object) null, (Class) class0);
      // Undeclared exception!
      try {
        objectRef0.hashCode();
        fail("Expecting exception: NullPointerException");
      } catch(NullPointerException e) {
      }
  }

  @Test
  public void test1()  throws Throwable  {
      ObjID objID0 = new ObjID();
      Class<?> class0 = Callback.class;
      ObjectRef objectRef0 = new ObjectRef(objID0, (Object) "", (Class) class0);
      ObjID objID1 = objectRef0.getObjID();
      assertNotNull(objID1);
      assertEquals("[-641d79ff:13f915623a2:-77a5, 4864766068729364169]", objID0.toString());
  }

  @Test
  public void test2()  throws Throwable  {
      Class<?> class0 = ObjID.class;
      ObjectRef objectRef0 = new ObjectRef((ObjID) null, (Object) null, (Class) class0);
      URI[] uRIArray0 = objectRef0.getURIs();
      assertNotNull(uRIArray0);
  }

  @Test
  public void test3()  throws Throwable  {
      ObjID objID0 = new ObjID();
      Class<?> class0 = Callback.class;
      ObjectRef objectRef0 = new ObjectRef(objID0, (Object) "", (Class) class0);
      String string0 = (String)objectRef0.getObject();
      assertNotNull(string0);
      assertEquals("[-641d79ff:13f915623a2:-77a3, 8072192609154729679]", objID0.toString());
  }

  @Test
  public void test4()  throws Throwable  {
      ObjID objID0 = new ObjID((-174));
      URI uRI0 = new URI();
      Class<?> class0 = InputStream.class;
      ObjectRef objectRef0 = new ObjectRef(objID0, (Object) uRI0, (Class) class0);
      try {
        objectRef0.getProxy(uRI0);
        fail("Expecting exception: NoSuchObjectException");
      } catch(NoSuchObjectException e) {
        /*
         * Object not exported on URI=
         */
      }
  }

  @Test
  public void test5()  throws Throwable  {
      ObjID objID0 = new ObjID((-174));
      URI uRI0 = new URI();
      Class<?> class0 = InputStream.class;
      ObjectRef objectRef0 = new ObjectRef(objID0, (Object) uRI0, (Class) class0);
      boolean boolean0 = objectRef0.equals((Object) ":");
      assertEquals(false, boolean0);
  }

  @Test
  public void test6()  throws Throwable  {
      ObjID objID0 = new ObjID((-174));
      URI uRI0 = new URI();
      Class<?> class0 = InputStream.class;
      ObjectRef objectRef0 = new ObjectRef(objID0, (Object) uRI0, (Class) class0);
      boolean boolean0 = objectRef0.equals((Object) objectRef0);
      assertEquals(true, boolean0);
  }

  @Test
  public void test7()  throws Throwable  {
      ObjID objID0 = new ObjID((-174));
      URI uRI0 = new URI();
      Class<?> class0 = InputStream.class;
      ObjectRef objectRef0 = new ObjectRef(objID0, (Object) uRI0, (Class) class0);
      Class<Object> class1 = objectRef0.getProxyClass();
      assertNotNull(class1);
      
      ObjectRef objectRef1 = new ObjectRef(objID0, (Object) uRI0, (Class) class1);
      boolean boolean0 = objectRef0.equals((Object) objectRef1);
      assertEquals(true, boolean0);
  }
}
