/*
 * This file was automatically generated by EvoSuite
 */

package org.exolab.jms.net.tcp;

import org.junit.Test;
import org.junit.runner.RunWith;
import org.evosuite.junit.EvoSuiteRunner;
import static org.junit.Assert.*;
import java.security.Principal;
import javax.management.remote.JMXPrincipal;
import org.exolab.jms.authentication.AuthenticationMgr;
import org.exolab.jms.authentication.UserManager;
import org.exolab.jms.config.Configuration;
import org.exolab.jms.net.connector.Authenticator;
import org.exolab.jms.net.connector.ConnectionFactory;
import org.exolab.jms.net.connector.ConnectionManager;
import org.exolab.jms.net.connector.ConnectionRequestInfo;
import org.exolab.jms.net.connector.ResourceException;
import org.exolab.jms.net.connector.URIRequestInfo;
import org.exolab.jms.net.tcp.TCPSManagedConnectionFactory;
import org.exolab.jms.net.tcp.TCPSRequestInfo;
import org.exolab.jms.net.uri.URI;
import org.exolab.jms.net.util.Properties;
import org.exolab.jms.persistence.DatabaseService;
import org.junit.BeforeClass;

@RunWith(EvoSuiteRunner.class)
public class TestTCPSManagedConnectionFactory {

  @BeforeClass 
  public static void initEvoSuiteFramework(){ 
    org.evosuite.Properties.REPLACE_CALLS = true; 
  } 


  @Test
  public void test0()  throws Throwable  {
      TCPSManagedConnectionFactory tCPSManagedConnectionFactory0 = new TCPSManagedConnectionFactory();
      ConnectionFactory connectionFactory0 = tCPSManagedConnectionFactory0.createConnectionFactory((ConnectionManager) null);
      assertNotNull(connectionFactory0);
  }

  @Test
  public void test1()  throws Throwable  {
      TCPSManagedConnectionFactory tCPSManagedConnectionFactory0 = new TCPSManagedConnectionFactory();
      URI uRI0 = new URI();
      TCPSRequestInfo tCPSRequestInfo0 = new TCPSRequestInfo(uRI0);
      // Undeclared exception!
      try {
        tCPSManagedConnectionFactory0.createManagedConnection((Principal) null, (ConnectionRequestInfo) tCPSRequestInfo0);
        fail("Expecting exception: NoClassDefFoundError");
      } catch(NoClassDefFoundError e) {
        /*
         * Could not initialize class javax.crypto.JceSecurityManager
         */
      }
  }

  @Test
  public void test2()  throws Throwable  {
      TCPSManagedConnectionFactory tCPSManagedConnectionFactory0 = new TCPSManagedConnectionFactory();
      JMXPrincipal jMXPrincipal0 = new JMXPrincipal("z9=dT*RWDTsSU3");
      try {
        tCPSManagedConnectionFactory0.createManagedConnection((Principal) jMXPrincipal0, (ConnectionRequestInfo) null);
        fail("Expecting exception: ResourceException");
      } catch(ResourceException e) {
        /*
         * Argument 'info' must be of type org.exolab.jms.net.tcp.TCPSRequestInfo
         */
      }
  }

  @Test
  public void test3()  throws Throwable  {
      TCPSManagedConnectionFactory tCPSManagedConnectionFactory0 = new TCPSManagedConnectionFactory();
      URI uRI0 = new URI();
      Properties properties0 = new Properties("o)}9?o<@s");
      TCPSRequestInfo tCPSRequestInfo0 = new TCPSRequestInfo(uRI0, properties0);
      // Undeclared exception!
      try {
        tCPSManagedConnectionFactory0.createManagedConnectionAcceptor((Authenticator) null, (ConnectionRequestInfo) tCPSRequestInfo0);
        fail("Expecting exception: IllegalArgumentException");
      } catch(IllegalArgumentException e) {
        /*
         * Argument 'authenticator' is null
         */
      }
  }

  @Test
  public void test4()  throws Throwable  {
      TCPSManagedConnectionFactory tCPSManagedConnectionFactory0 = new TCPSManagedConnectionFactory();
      URI uRI0 = new URI();
      Configuration configuration0 = new Configuration();
      DatabaseService databaseService0 = new DatabaseService(configuration0);
      UserManager userManager0 = new UserManager(configuration0, databaseService0);
      URIRequestInfo uRIRequestInfo0 = new URIRequestInfo(uRI0);
      AuthenticationMgr authenticationMgr0 = new AuthenticationMgr(userManager0);
      try {
        tCPSManagedConnectionFactory0.createManagedConnectionAcceptor((Authenticator) authenticationMgr0, (ConnectionRequestInfo) uRIRequestInfo0);
        fail("Expecting exception: ResourceException");
      } catch(ResourceException e) {
        /*
         * Argument 'info' must be of type org.exolab.jms.net.tcp.TCPSRequestInfo
         */
      }
  }
}
