/*
 * This file was automatically generated by EvoSuite
 */

package org.exolab.jms.net.tunnel;

import org.junit.Test;
import org.junit.runner.RunWith;
import org.evosuite.junit.EvoSuiteRunner;
import static org.junit.Assert.*;
import java.net.Socket;
import org.exolab.jms.net.tunnel.SocketInfo;
import org.junit.BeforeClass;

@RunWith(EvoSuiteRunner.class)
public class TestSocketInfo {

  @BeforeClass 
  public static void initEvoSuiteFramework(){ 
    org.evosuite.Properties.REPLACE_CALLS = true; 
  } 


  @Test
  public void test0()  throws Throwable  {
      SocketInfo socketInfo0 = new SocketInfo("~U)D821c}=*2IHCGw34", (Socket) null);
      String string0 = socketInfo0.getId();
      assertEquals("~U)D821c}=*2IHCGw34", string0);
  }

  @Test
  public void test1()  throws Throwable  {
      SocketInfo socketInfo0 = new SocketInfo("~U)D821c}=*2IHCGw34", (Socket) null);
      long long0 = socketInfo0.getUsed();
      assertEquals(0L, long0);
  }

  @Test
  public void test2()  throws Throwable  {
      SocketInfo socketInfo0 = new SocketInfo("~U)D821c}=*2IHCGw34", (Socket) null);
      Socket socket0 = socketInfo0.getSocket();
      assertNull(socket0);
  }
}
