/*
 * This file was automatically generated by EvoSuite
 */

package org.exolab.jms.net.http;

import org.junit.Test;
import org.junit.runner.RunWith;
import org.evosuite.junit.EvoSuiteRunner;
import static org.junit.Assert.*;
import com.sun.net.ssl.internal.www.protocol.https.Handler;
import java.io.IOException;
import java.net.MalformedURLException;
import java.net.URL;
import java.net.URLStreamHandler;
import org.exolab.jms.net.http.HTTPOutputStream;
import org.exolab.jms.net.http.HTTPRequestInfo;
import org.exolab.jms.net.uri.URI;
import org.junit.BeforeClass;

@RunWith(EvoSuiteRunner.class)
public class TestHTTPOutputStream {

  @BeforeClass 
  public static void initEvoSuiteFramework(){ 
    org.evosuite.Properties.REPLACE_CALLS = true; 
  } 


  @Test
  public void test0()  throws Throwable  {
      URI uRI0 = new URI();
      HTTPRequestInfo hTTPRequestInfo0 = new HTTPRequestInfo(uRI0);
      HTTPOutputStream hTTPOutputStream0 = new HTTPOutputStream("v#aFGLaP=(xqg}Ex", (URL) null, 13, hTTPRequestInfo0);
      byte[] byteArray0 = new byte[12];
      hTTPOutputStream0.write(byteArray0);
      hTTPOutputStream0.write((int) (byte) (-107));
      // Undeclared exception!
      try {
        hTTPOutputStream0.write((int) (byte)0);
        fail("Expecting exception: NullPointerException");
      } catch(NullPointerException e) {
      }
  }

  @Test
  public void test1()  throws Throwable  {
      Handler handler0 = new Handler("Q8", 12);
      URL uRL0 = new URL("Q8", "Q8", 12, "Q8", (URLStreamHandler) handler0);
      byte[] byteArray0 = new byte[26];
      HTTPOutputStream hTTPOutputStream0 = new HTTPOutputStream("Q8", uRL0, 12, (HTTPRequestInfo) null);
      // Undeclared exception!
      try {
        hTTPOutputStream0.write(byteArray0, 12, (int) (byte)50);
        fail("Expecting exception: NullPointerException");
      } catch(NullPointerException e) {
      }
  }
}
