/*
 * This file was automatically generated by EvoSuite
 */

package org.exolab.jms.net.http;

import org.junit.Test;
import org.junit.runner.RunWith;
import org.evosuite.junit.EvoSuiteRunner;
import static org.junit.Assert.*;
import java.io.IOException;
import java.util.concurrent.ExecutorService;
import java.util.concurrent.Executors;
import java.util.concurrent.Future;
import java.util.concurrent.TimeUnit;
import org.evosuite.Properties.SandboxMode;
import org.evosuite.sandbox.Sandbox;
import org.exolab.jms.net.connector.ResourceException;
import org.exolab.jms.net.http.HTTPEndpoint;
import org.exolab.jms.net.http.HTTPRequestInfo;
import org.exolab.jms.net.uri.URI;
import org.exolab.jms.net.util.Properties;
import org.exolab.jms.net.util.SSLProperties;
import org.junit.After;
import org.junit.AfterClass;
import org.junit.Before;
import org.junit.BeforeClass;

@RunWith(EvoSuiteRunner.class)
public class TestHTTPEndpoint {

  private static ExecutorService executor; 

  @BeforeClass 
  public static void initEvoSuiteFramework(){ 
    org.evosuite.Properties.REPLACE_CALLS = true; 
    org.evosuite.Properties.SANDBOX_MODE = SandboxMode.RECOMMENDED; 
    Sandbox.initializeSecurityManagerForSUT(); 
    executor = Executors.newCachedThreadPool(); 
  } 

  @AfterClass 
  public static void clearEvoSuiteFramework(){ 
    executor.shutdownNow(); 
    Sandbox.resetDefaultSecurityManager(); 
  } 

  @Before 
  public void initTestCase(){ 
    Sandbox.goingToExecuteSUTCode(); 
  } 

  @After 
  public void doneWithTestCase(){ 
    Sandbox.doneWithExecutingSUTCode(); 
  } 


  @Test
  public void test0()  throws Throwable  {
    Future<?> future = executor.submit(new Runnable(){ 
            public void run() { 
        try {
          URI uRI0 = new URI("https", "https", "https", "https", "https");
          HTTPRequestInfo hTTPRequestInfo0 = new HTTPRequestInfo(uRI0);
          SSLProperties sSLProperties0 = new SSLProperties();
          hTTPRequestInfo0.setSSLProperties(sSLProperties0);
          HTTPEndpoint hTTPEndpoint0 = null;
          try {
            hTTPEndpoint0 = new HTTPEndpoint(hTTPRequestInfo0);
            fail("Expecting exception: SecurityException");
          } catch(SecurityException e) {
            /*
             * Security manager blocks (\"java.net.SocketPermission\" \"httpshttps:443\" \"connect,resolve\")
             * java.lang.Thread.getStackTrace(Thread.java:1567)
             * org.evosuite.sandbox.MSecurityManager.checkPermission(MSecurityManager.java:303)
             * java.lang.SecurityManager.checkConnect(SecurityManager.java:1051)
             * sun.net.www.http.HttpClient.openServer(HttpClient.java:466)
             * sun.net.www.protocol.https.HttpsClient.<init>(HttpsClient.java:278)
             * sun.net.www.protocol.https.HttpsClient.New(HttpsClient.java:335)
             * sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.getNewHttpClient(AbstractDelegateHttpsURLConnection.java:191)
             * sun.net.www.protocol.http.HttpURLConnection.plainConnect(HttpURLConnection.java:928)
             * sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.connect(AbstractDelegateHttpsURLConnection.java:177)
             * sun.net.www.protocol.https.HttpsURLConnectionImpl.connect(HttpsURLConnectionImpl.java:153)
             * org.exolab.jms.net.http.TunnelHelper.connect(TunnelHelper.java:114)
             * org.exolab.jms.net.http.HTTPEndpoint.getConnection(HTTPEndpoint.java:242)
             * org.exolab.jms.net.http.HTTPEndpoint.<init>(HTTPEndpoint.java:168)
             * sun.reflect.GeneratedConstructorAccessor33.newInstance(Unknown Source)
             * sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
             * java.lang.reflect.Constructor.newInstance(Constructor.java:525)
             * org.evosuite.testcase.ConstructorStatement$1.execute(ConstructorStatement.java:226)
             * org.evosuite.testcase.AbstractStatement.exceptionHandler(AbstractStatement.java:142)
             * org.evosuite.testcase.ConstructorStatement.execute(ConstructorStatement.java:188)
             * org.evosuite.testcase.TestRunnable.call(TestRunnable.java:291)
             * org.evosuite.testcase.TestRunnable.call(TestRunnable.java:44)
             * java.util.concurrent.FutureTask$Sync.innerRun(FutureTask.java:334)
             * java.util.concurrent.FutureTask.run(FutureTask.java:166)
             * java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1110)
             * java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:603)
             * java.lang.Thread.run(Thread.java:722)
             */
          }
        } catch(Throwable t) {
            // Need to catch declared exceptions
        }
      } 
    }); 
    future.get(6000, TimeUnit.MILLISECONDS); 
  }

  @Test
  public void test1()  throws Throwable  {
    Future<?> future = executor.submit(new Runnable(){ 
            public void run() { 
        try {
          URI uRI0 = new URI("http", "http", "http", "http", "http");
          Properties properties0 = new Properties("http");
          HTTPRequestInfo hTTPRequestInfo0 = new HTTPRequestInfo(uRI0, properties0);
          hTTPRequestInfo0.setProxyHost("http");
          HTTPEndpoint hTTPEndpoint0 = null;
          try {
            hTTPEndpoint0 = new HTTPEndpoint(hTTPRequestInfo0);
            fail("Expecting exception: SecurityException");
          } catch(SecurityException e) {
            /*
             * Security manager blocks (\"java.net.SocketPermission\" \"httphttp:80\" \"connect,resolve\")
             * java.lang.Thread.getStackTrace(Thread.java:1567)
             * org.evosuite.sandbox.MSecurityManager.checkPermission(MSecurityManager.java:303)
             * java.lang.SecurityManager.checkConnect(SecurityManager.java:1051)
             * sun.net.www.http.HttpClient.openServer(HttpClient.java:466)
             * sun.net.www.http.HttpClient.<init>(HttpClient.java:213)
             * sun.net.www.http.HttpClient.New(HttpClient.java:300)
             * sun.net.www.http.HttpClient.New(HttpClient.java:316)
             * sun.net.www.protocol.http.HttpURLConnection.getNewHttpClient(HttpURLConnection.java:992)
             * sun.net.www.protocol.http.HttpURLConnection.plainConnect(HttpURLConnection.java:928)
             * sun.net.www.protocol.http.HttpURLConnection.connect(HttpURLConnection.java:846)
             * org.exolab.jms.net.http.TunnelHelper.connect(TunnelHelper.java:114)
             * org.exolab.jms.net.http.HTTPEndpoint.getConnection(HTTPEndpoint.java:242)
             * org.exolab.jms.net.http.HTTPEndpoint.<init>(HTTPEndpoint.java:168)
             * sun.reflect.GeneratedConstructorAccessor33.newInstance(Unknown Source)
             * sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
             * java.lang.reflect.Constructor.newInstance(Constructor.java:525)
             * org.evosuite.testcase.ConstructorStatement$1.execute(ConstructorStatement.java:226)
             * org.evosuite.testcase.AbstractStatement.exceptionHandler(AbstractStatement.java:142)
             * org.evosuite.testcase.ConstructorStatement.execute(ConstructorStatement.java:188)
             * org.evosuite.testcase.TestRunnable.call(TestRunnable.java:291)
             * org.evosuite.testcase.TestRunnable.call(TestRunnable.java:44)
             * java.util.concurrent.FutureTask$Sync.innerRun(FutureTask.java:334)
             * java.util.concurrent.FutureTask.run(FutureTask.java:166)
             * java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1110)
             * java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:603)
             * java.lang.Thread.run(Thread.java:722)
             */
          }
        } catch(Throwable t) {
            // Need to catch declared exceptions
        }
      } 
    }); 
    future.get(6000, TimeUnit.MILLISECONDS); 
  }

  @Test
  public void test2()  throws Throwable  {
    Future<?> future = executor.submit(new Runnable(){ 
            public void run() { 
        try {
          URI uRI0 = new URI("https", "https", "https", "https", "https");
          HTTPRequestInfo hTTPRequestInfo0 = new HTTPRequestInfo(uRI0);
          hTTPRequestInfo0.setProxyHost("https");
          HTTPEndpoint hTTPEndpoint0 = null;
          try {
            hTTPEndpoint0 = new HTTPEndpoint(hTTPRequestInfo0);
            fail("Expecting exception: SecurityException");
          } catch(SecurityException e) {
            /*
             * Security manager blocks (\"java.net.SocketPermission\" \"httpshttps:443\" \"connect,resolve\")
             * java.lang.Thread.getStackTrace(Thread.java:1567)
             * org.evosuite.sandbox.MSecurityManager.checkPermission(MSecurityManager.java:303)
             * java.lang.SecurityManager.checkConnect(SecurityManager.java:1051)
             * sun.net.www.http.HttpClient.openServer(HttpClient.java:466)
             * sun.net.www.protocol.https.HttpsClient.<init>(HttpsClient.java:278)
             * sun.net.www.protocol.https.HttpsClient.New(HttpsClient.java:335)
             * sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.getNewHttpClient(AbstractDelegateHttpsURLConnection.java:191)
             * sun.net.www.protocol.http.HttpURLConnection.plainConnect(HttpURLConnection.java:928)
             * sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.connect(AbstractDelegateHttpsURLConnection.java:177)
             * sun.net.www.protocol.https.HttpsURLConnectionImpl.connect(HttpsURLConnectionImpl.java:153)
             * org.exolab.jms.net.http.TunnelHelper.connect(TunnelHelper.java:114)
             * org.exolab.jms.net.http.HTTPEndpoint.getConnection(HTTPEndpoint.java:242)
             * org.exolab.jms.net.http.HTTPEndpoint.<init>(HTTPEndpoint.java:168)
             * sun.reflect.GeneratedConstructorAccessor33.newInstance(Unknown Source)
             * sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
             * java.lang.reflect.Constructor.newInstance(Constructor.java:525)
             * org.evosuite.testcase.ConstructorStatement$1.execute(ConstructorStatement.java:226)
             * org.evosuite.testcase.AbstractStatement.exceptionHandler(AbstractStatement.java:142)
             * org.evosuite.testcase.ConstructorStatement.execute(ConstructorStatement.java:188)
             * org.evosuite.testcase.TestRunnable.call(TestRunnable.java:291)
             * org.evosuite.testcase.TestRunnable.call(TestRunnable.java:44)
             * java.util.concurrent.FutureTask$Sync.innerRun(FutureTask.java:334)
             * java.util.concurrent.FutureTask.run(FutureTask.java:166)
             * java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1110)
             * java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:603)
             * java.lang.Thread.run(Thread.java:722)
             */
          }
        } catch(Throwable t) {
            // Need to catch declared exceptions
        }
      } 
    }); 
    future.get(6000, TimeUnit.MILLISECONDS); 
  }

  @Test
  public void test3()  throws Throwable  {
      URI uRI0 = new URI("https", "https", "https", "https", "https");
      HTTPRequestInfo hTTPRequestInfo0 = new HTTPRequestInfo(uRI0);
      hTTPRequestInfo0.setProxyPort((-16));
      hTTPRequestInfo0.setProxyHost("https");
      HTTPEndpoint hTTPEndpoint0 = null;
      try {
        hTTPEndpoint0 = new HTTPEndpoint(hTTPRequestInfo0);
        fail("Expecting exception: IllegalArgumentException");
      } catch(IllegalArgumentException e) {
        /*
         * port out of range:-16
         */
      }
  }
}
