/*
 * This file was automatically generated by EvoSuite
 */

package org.exolab.jms.net;

import org.junit.Test;
import org.junit.runner.RunWith;
import org.evosuite.junit.EvoSuiteRunner;
import static org.junit.Assert.*;
import java.rmi.server.ObjID;
import org.exolab.jms.net.Callback;
import org.exolab.jms.net.CallbackService;
import org.exolab.jms.net.CallbackServiceImpl__Proxy;
import org.exolab.jms.net.connector.Connection;
import org.exolab.jms.net.invoke.LoggingCallback__Proxy;
import org.exolab.jms.net.invoke.RecursiveCallback;
import org.exolab.jms.net.orb.UnicastDelegate;
import org.exolab.jms.net.proxy.Delegate;
import org.exolab.jms.net.proxy.RemoteInvocationException;
import org.junit.BeforeClass;

@RunWith(EvoSuiteRunner.class)
public class TestCallbackServiceImpl__Proxy {

  @BeforeClass 
  public static void initEvoSuiteFramework(){ 
    org.evosuite.Properties.REPLACE_CALLS = true; 
  } 


  @Test
  public void test0()  throws Throwable  {
      CallbackServiceImpl__Proxy callbackServiceImpl__Proxy0 = new CallbackServiceImpl__Proxy((Delegate) null);
      RecursiveCallback recursiveCallback0 = new RecursiveCallback((CallbackService) callbackServiceImpl__Proxy0, (-1954));
      // Undeclared exception!
      try {
        callbackServiceImpl__Proxy0.addCallback((Callback) recursiveCallback0);
        fail("Expecting exception: RemoteInvocationException");
      } catch(RemoteInvocationException e) {
      }
  }

  @Test
  public void test1()  throws Throwable  {
      ObjID objID0 = new ObjID();
      UnicastDelegate unicastDelegate0 = new UnicastDelegate(objID0, (Connection) null);
      CallbackServiceImpl__Proxy callbackServiceImpl__Proxy0 = new CallbackServiceImpl__Proxy((Delegate) unicastDelegate0);
      // Undeclared exception!
      try {
        callbackServiceImpl__Proxy0.invoke((Object) "");
        fail("Expecting exception: RemoteInvocationException");
      } catch(RemoteInvocationException e) {
      }
  }

  @Test
  public void test2()  throws Throwable  {
      UnicastDelegate unicastDelegate0 = new UnicastDelegate((ObjID) null, "org.exolab.jms.net.orb.UnicastDelegate");
      CallbackServiceImpl__Proxy callbackServiceImpl__Proxy0 = new CallbackServiceImpl__Proxy((Delegate) unicastDelegate0);
      LoggingCallback__Proxy loggingCallback__Proxy0 = new LoggingCallback__Proxy((Delegate) unicastDelegate0);
      // Undeclared exception!
      try {
        callbackServiceImpl__Proxy0.removeCallback((Callback) loggingCallback__Proxy0);
        fail("Expecting exception: RemoteInvocationException");
      } catch(RemoteInvocationException e) {
      }
  }

  @Test
  public void test3()  throws Throwable  {
      CallbackServiceImpl__Proxy callbackServiceImpl__Proxy0 = new CallbackServiceImpl__Proxy((Delegate) null);
      // Undeclared exception!
      try {
        callbackServiceImpl__Proxy0.getCallbacks();
        fail("Expecting exception: RemoteInvocationException");
      } catch(RemoteInvocationException e) {
      }
  }
}
