/*
 * This file was automatically generated by EvoSuite
 */

package org.exolab.jms.tools.db;

import org.junit.Test;
import org.junit.runner.RunWith;
import org.evosuite.junit.EvoSuiteRunner;
import static org.junit.Assert.*;
import org.exolab.jms.tools.db.Descriptor;
import org.junit.BeforeClass;

@RunWith(EvoSuiteRunner.class)
public class TestDescriptor {

  @BeforeClass 
  public static void initEvoSuiteFramework(){ 
    org.evosuite.Properties.REPLACE_CALLS = true; 
  } 


  @Test
  public void test0()  throws Throwable  {
      Descriptor descriptor0 = Descriptor.getDescriptor("DOUBLE");
      assertEquals(8, descriptor0.getType());
  }

  @Test
  public void test1()  throws Throwable  {
      Descriptor descriptor0 = Descriptor.getDescriptor(8);
      assertNotNull(descriptor0);
      
      String string0 = descriptor0.getName();
      assertEquals("DOUBLE", string0);
      assertNotNull(string0);
  }

  @Test
  public void test2()  throws Throwable  {
      Descriptor descriptor0 = Descriptor.getDescriptor(8);
      assertNotNull(descriptor0);
      
      int int0 = descriptor0.getType();
      assertEquals(8, int0);
  }
}
