/*
 * This file was automatically generated by EvoSuite
 */

package org.exolab.jms.tools.db;

import org.junit.Test;
import org.junit.runner.RunWith;
import org.evosuite.junit.EvoSuiteRunner;
import static org.junit.Assert.*;
import org.exolab.castor.xml.ValidationException;
import org.exolab.jms.tools.db.Deprecated;
import org.exolab.jms.tools.db.DeprecatedDescriptor;
import org.junit.BeforeClass;

@RunWith(EvoSuiteRunner.class)
public class TestDeprecatedDescriptor {

  @BeforeClass 
  public static void initEvoSuiteFramework(){ 
    org.evosuite.Properties.REPLACE_CALLS = true; 
  } 


  @Test
  public void test0()  throws Throwable  {
      DeprecatedDescriptor deprecatedDescriptor0 = new DeprecatedDescriptor();
      Deprecated deprecated0 = new Deprecated();
      try {
        deprecatedDescriptor0.validate((Object) deprecated0);
        fail("Expecting exception: ValidationException");
      } catch(ValidationException e) {
        /*
         * name is a required field.
         */
      }
  }

  @Test
  public void test1()  throws Throwable  {
      DeprecatedDescriptor deprecatedDescriptor0 = new DeprecatedDescriptor();
      deprecatedDescriptor0.getExtends();
      assertEquals("deprecated", deprecatedDescriptor0.getXMLName());
      assertEquals("http://www.openjms.org/database/schema", deprecatedDescriptor0.getNameSpaceURI());
  }

  @Test
  public void test2()  throws Throwable  {
      DeprecatedDescriptor deprecatedDescriptor0 = new DeprecatedDescriptor();
      String string0 = deprecatedDescriptor0.getXMLName();
      assertEquals("deprecated", string0);
      assertEquals("http://www.openjms.org/database/schema", deprecatedDescriptor0.getNameSpaceURI());
      assertNotNull(string0);
  }

  @Test
  public void test3()  throws Throwable  {
      DeprecatedDescriptor deprecatedDescriptor0 = new DeprecatedDescriptor();
      deprecatedDescriptor0.getIdentity();
      assertEquals("deprecated", deprecatedDescriptor0.getXMLName());
      assertEquals("http://www.openjms.org/database/schema", deprecatedDescriptor0.getNameSpaceURI());
  }

  @Test
  public void test4()  throws Throwable  {
      DeprecatedDescriptor deprecatedDescriptor0 = new DeprecatedDescriptor();
      DeprecatedDescriptor deprecatedDescriptor1 = (DeprecatedDescriptor)deprecatedDescriptor0.getValidator();
      assertEquals("http://www.openjms.org/database/schema", deprecatedDescriptor0.getNameSpaceURI());
      assertEquals("deprecated", deprecatedDescriptor0.getXMLName());
      assertEquals("http://www.openjms.org/database/schema", deprecatedDescriptor1.getNameSpaceURI());
  }

  @Test
  public void test5()  throws Throwable  {
      DeprecatedDescriptor deprecatedDescriptor0 = new DeprecatedDescriptor();
      String string0 = deprecatedDescriptor0.getNameSpaceURI();
      assertNotNull(string0);
      assertEquals("deprecated", deprecatedDescriptor0.getXMLName());
      assertEquals("http://www.openjms.org/database/schema", string0);
  }

  @Test
  public void test6()  throws Throwable  {
      DeprecatedDescriptor deprecatedDescriptor0 = new DeprecatedDescriptor();
      deprecatedDescriptor0.getNameSpacePrefix();
      assertEquals("http://www.openjms.org/database/schema", deprecatedDescriptor0.getNameSpaceURI());
      assertEquals("deprecated", deprecatedDescriptor0.getXMLName());
  }

  @Test
  public void test7()  throws Throwable  {
      DeprecatedDescriptor deprecatedDescriptor0 = new DeprecatedDescriptor();
      deprecatedDescriptor0.getAccessMode();
      assertEquals("deprecated", deprecatedDescriptor0.getXMLName());
      assertEquals("http://www.openjms.org/database/schema", deprecatedDescriptor0.getNameSpaceURI());
  }
}
