/*
 * This file was automatically generated by EvoSuite
 */

package org.exolab.jms.tools.db;

import org.junit.Test;
import org.junit.runner.RunWith;
import org.evosuite.junit.EvoSuiteRunner;
import static org.junit.Assert.*;
import org.exolab.castor.mapping.ClassDescriptor;
import org.exolab.castor.mapping.MappingException;
import org.exolab.castor.xml.ValidationContext;
import org.exolab.castor.xml.ValidationException;
import org.exolab.castor.xml.util.XMLClassDescriptorAdapter;
import org.exolab.jms.tools.db.Attribute;
import org.exolab.jms.tools.db.AttributeDescriptor;
import org.junit.BeforeClass;

@RunWith(EvoSuiteRunner.class)
public class TestAttributeDescriptor {

  @BeforeClass 
  public static void initEvoSuiteFramework(){ 
    org.evosuite.Properties.REPLACE_CALLS = true; 
  } 


  @Test
  public void test0()  throws Throwable  {
      AttributeDescriptor attributeDescriptor0 = new AttributeDescriptor();
      XMLClassDescriptorAdapter xMLClassDescriptorAdapter0 = new XMLClassDescriptorAdapter((ClassDescriptor) attributeDescriptor0, "m]");
      assertEquals("attribute", attributeDescriptor0.getXMLName());
      assertEquals("http://www.openjms.org/database/schema", attributeDescriptor0.getNameSpaceURI());
  }

  @Test
  public void test1()  throws Throwable  {
      Attribute attribute0 = new Attribute();
      attribute0.setName("ET2NV!");
      boolean boolean0 = attribute0.isValid();
      assertEquals(false, boolean0);
  }

  @Test
  public void test2()  throws Throwable  {
      AttributeDescriptor attributeDescriptor0 = new AttributeDescriptor();
      attributeDescriptor0.getNameSpacePrefix();
      assertEquals("http://www.openjms.org/database/schema", attributeDescriptor0.getNameSpaceURI());
      assertEquals("attribute", attributeDescriptor0.getXMLName());
  }

  @Test
  public void test3()  throws Throwable  {
      AttributeDescriptor attributeDescriptor0 = new AttributeDescriptor();
      String string0 = attributeDescriptor0.getNameSpaceURI();
      assertEquals("attribute", attributeDescriptor0.getXMLName());
      assertNotNull(string0);
      assertEquals("http://www.openjms.org/database/schema", string0);
  }

  @Test
  public void test4()  throws Throwable  {
      AttributeDescriptor attributeDescriptor0 = new AttributeDescriptor();
      attributeDescriptor0.getAccessMode();
      assertEquals("attribute", attributeDescriptor0.getXMLName());
      assertEquals("http://www.openjms.org/database/schema", attributeDescriptor0.getNameSpaceURI());
  }

  @Test
  public void test5()  throws Throwable  {
      Attribute attribute0 = new Attribute();
      attribute0.setType("ET2NV!");
      attribute0.setName("ET2NV!");
      boolean boolean0 = attribute0.isValid();
      assertEquals(true, boolean0);
  }

  @Test
  public void test6()  throws Throwable  {
      AttributeDescriptor attributeDescriptor0 = new AttributeDescriptor();
      Attribute attribute0 = new Attribute();
      ValidationContext validationContext0 = new ValidationContext();
      attribute0.setType("ET2NV!");
      assertEquals(false, attribute0.isValid());
      
      attribute0.setName("ET2NV!");
      attribute0.setUnique(true);
      attributeDescriptor0.validate((Object) attribute0, validationContext0);
      assertEquals("http://www.openjms.org/database/schema", attributeDescriptor0.getNameSpaceURI());
  }

  @Test
  public void test7()  throws Throwable  {
      AttributeDescriptor attributeDescriptor0 = new AttributeDescriptor();
      Attribute attribute0 = new Attribute();
      ValidationContext validationContext0 = new ValidationContext();
      attribute0.setType("ET2NV!");
      assertEquals(false, attribute0.isValid());
      
      attribute0.setName("ET2NV!");
      attribute0.setNotNull(true);
      attributeDescriptor0.validate((Object) attribute0, validationContext0);
      assertEquals("http://www.openjms.org/database/schema", attributeDescriptor0.getNameSpaceURI());
  }
}
