/*
 * This file was automatically generated by EvoSuite
 */

package org.exolab.jms.net.util;

import org.junit.Test;
import org.junit.runner.RunWith;
import org.evosuite.junit.EvoSuiteRunner;
import static org.junit.Assert.*;
import java.io.BufferedOutputStream;
import java.io.IOException;
import java.io.NotSerializableException;
import java.io.ObjectInput;
import java.io.ObjectOutput;
import java.io.ObjectOutputStream;
import java.io.OutputStream;
import java.io.PipedOutputStream;
import org.exolab.jms.net.util.SerializationHelper;
import org.junit.BeforeClass;

@RunWith(EvoSuiteRunner.class)
public class TestSerializationHelper {

  @BeforeClass 
  public static void initEvoSuiteFramework(){ 
    org.evosuite.Properties.REPLACE_CALLS = true; 
  } 


  @Test
  public void test0()  throws Throwable  {
      Class<?> class0 = CharSequence.class;
      Object object0 = new Object();
      PipedOutputStream pipedOutputStream0 = new PipedOutputStream();
      BufferedOutputStream bufferedOutputStream0 = new BufferedOutputStream((OutputStream) pipedOutputStream0);
      ObjectOutputStream objectOutputStream0 = new ObjectOutputStream((OutputStream) bufferedOutputStream0);
      try {
        SerializationHelper.write((Class) class0, object0, (ObjectOutput) objectOutputStream0);
        fail("Expecting exception: NotSerializableException");
      } catch(NotSerializableException e) {
        /*
         * java.lang.Object
         */
      }
  }

  @Test
  public void test1()  throws Throwable  {
      Class<?> class0 = SerializationHelper.class;
      // Undeclared exception!
      try {
        SerializationHelper.read((Class) class0, (ObjectInput) null);
        fail("Expecting exception: NullPointerException");
      } catch(NullPointerException e) {
      }
  }
}
