package org.exolab.jms.message;

import static org.junit.Assert.*;

import java.io.ObjectInput;

import javax.jms.JMSException;

import org.junit.After;
import org.junit.Before;
import org.junit.Test;
import org.mockito.Mockito;

public class MessageImplTest {

	MessageImpl MessageImpl;
	
	@Before
	public void setUp() throws Exception {
		
		MessageImpl = new MessageImpl();
	}

	@After
	public void tearDown() throws Exception {
	}

	//kh-11
	@Test
	public void testSetJMSMessageID() throws JMSException {
		
		String messageID = "ID:cedd46b8-ea42-1004-870d-ba41b45b960f"; //This example ID was generated by UUID generator
		MessageImpl.setJMSMessageID(messageID);
		assertEquals(messageID, MessageImpl.getJMSMessageID());
		
	}
	
	//kh-12
	@Test
	public void testSetJMSTimestamp() throws JMSException {
		
		long timestamp = 1615433220;
		MessageImpl.setJMSTimestamp(timestamp);
		assertEquals(timestamp, MessageImpl.getJMSTimestamp());
		
	}
	
	//kh-13
	@Test
	public void testSetWildcard() {
		
		String wildcardChar = "*";
		MessageImpl.setWildcard(wildcardChar);
		assertEquals(wildcardChar, MessageImpl.getWildcard());
		
	}
	
	//kh-14
	@Test
	public void testSetConsumerId() {
        
		long consumerID = 12345;
		MessageImpl.setConsumerId(consumerID);
		assertEquals(consumerID, MessageImpl.getConsumerId());
		
    }
	
	
	
	

}
