/*
 * This file was automatically generated by EvoSuite
 */

package org.exolab.jms.net.rmi;

import org.junit.Test;
import org.junit.runner.RunWith;
import org.evosuite.junit.EvoSuiteRunner;
import static org.junit.Assert.*;
import java.security.Principal;
import java.util.LinkedList;
import java.util.List;
import javax.management.remote.JMXPrincipal;
import org.evosuite.testcase.TestCaseExecutor;
import org.exolab.jms.authentication.AuthenticationMgr;
import org.exolab.jms.authentication.UserManager;
import org.exolab.jms.config.Configuration;
import org.exolab.jms.net.connector.Authenticator;
import org.exolab.jms.net.connector.ConnectionFactory;
import org.exolab.jms.net.connector.ConnectionManager;
import org.exolab.jms.net.connector.ConnectionRequestInfo;
import org.exolab.jms.net.connector.ManagedConnection;
import org.exolab.jms.net.connector.ManagedConnectionAcceptor;
import org.exolab.jms.net.connector.ResourceException;
import org.exolab.jms.net.rmi.RMIManagedConnectionFactory;
import org.exolab.jms.net.rmi.RMIRequestInfo;
import org.exolab.jms.net.uri.URI;
import org.exolab.jms.net.util.Properties;
import org.exolab.jms.persistence.DatabaseService;
import org.junit.BeforeClass;

@RunWith(EvoSuiteRunner.class)
public class TestRMIManagedConnectionFactory {

  @BeforeClass 
  public static void initEvoSuiteFramework(){ 
    org.evosuite.Properties.REPLACE_CALLS = true; 
  } 


  @Test
  public void test0()  throws Throwable  {
      RMIManagedConnectionFactory rMIManagedConnectionFactory0 = new RMIManagedConnectionFactory();
      ConnectionFactory connectionFactory0 = rMIManagedConnectionFactory0.createConnectionFactory((ConnectionManager) null);
      assertNotNull(connectionFactory0);
  }

  @Test
  public void test1()  throws Throwable  {
      RMIManagedConnectionFactory rMIManagedConnectionFactory0 = new RMIManagedConnectionFactory();
      JMXPrincipal jMXPrincipal0 = new JMXPrincipal("|");
      URI uRI0 = new URI();
      RMIRequestInfo rMIRequestInfo0 = new RMIRequestInfo(uRI0);
      rMIManagedConnectionFactory0.createManagedConnection((Principal) jMXPrincipal0, (ConnectionRequestInfo) rMIRequestInfo0);
  }

  @Test
  public void test2()  throws Throwable  {
      RMIManagedConnectionFactory rMIManagedConnectionFactory0 = new RMIManagedConnectionFactory();
      JMXPrincipal jMXPrincipal0 = new JMXPrincipal("0Tmu");
      try {
        rMIManagedConnectionFactory0.createManagedConnection((Principal) jMXPrincipal0, (ConnectionRequestInfo) null);
        fail("Expecting exception: ResourceException");
      } catch(ResourceException e) {
        /*
         * Argument 'info' must be of type org.exolab.jms.net.rmi.RMIRequestInfo
         */
      }
  }

  @Test
  public void test3()  throws Throwable  {
      RMIManagedConnectionFactory rMIManagedConnectionFactory0 = new RMIManagedConnectionFactory();
      URI uRI0 = new URI();
      Properties properties0 = new Properties("G'IDjbvveo(a5N:7wc ");
      RMIRequestInfo rMIRequestInfo0 = new RMIRequestInfo(uRI0, properties0);
      ManagedConnectionAcceptor managedConnectionAcceptor0 = rMIManagedConnectionFactory0.createManagedConnectionAcceptor((Authenticator) null, (ConnectionRequestInfo) rMIRequestInfo0);
      assertNotNull(managedConnectionAcceptor0);
  }

  @Test
  public void test4()  throws Throwable  {
      RMIManagedConnectionFactory rMIManagedConnectionFactory0 = new RMIManagedConnectionFactory();
      Configuration configuration0 = new Configuration();
      DatabaseService databaseService0 = new DatabaseService(configuration0);
      UserManager userManager0 = new UserManager(configuration0, databaseService0);
      AuthenticationMgr authenticationMgr0 = new AuthenticationMgr(userManager0);
      try {
        rMIManagedConnectionFactory0.createManagedConnectionAcceptor((Authenticator) authenticationMgr0, (ConnectionRequestInfo) null);
        fail("Expecting exception: ResourceException");
      } catch(ResourceException e) {
        /*
         * Argument 'info' must be of type org.exolab.jms.net.rmi.RMIRequestInfo
         */
      }
  }

  @Test
  public void test5()  throws Throwable  {
      RMIManagedConnectionFactory rMIManagedConnectionFactory0 = new RMIManagedConnectionFactory();
      ManagedConnection managedConnection0 = rMIManagedConnectionFactory0.matchManagedConnections((List) null, (Principal) null, (ConnectionRequestInfo) null);
      assertNull(managedConnection0);
  }

  @Test
  public void test6()  throws Throwable  {
      RMIManagedConnectionFactory rMIManagedConnectionFactory0 = new RMIManagedConnectionFactory();
      URI uRI0 = new URI();
      LinkedList<Integer> linkedList0 = new LinkedList<Integer>();
      JMXPrincipal jMXPrincipal0 = new JMXPrincipal("G'IDjbvveo(a5N:7wc ");
      Properties properties0 = new Properties("G'IDjbvveo(a5N:7wc ");
      RMIRequestInfo rMIRequestInfo0 = new RMIRequestInfo(uRI0, properties0);
      ManagedConnection managedConnection0 = rMIManagedConnectionFactory0.matchManagedConnections((List) linkedList0, (Principal) jMXPrincipal0, (ConnectionRequestInfo) rMIRequestInfo0);
      assertNull(managedConnection0);
  }

  @Test
  public void test7()  throws Throwable  {
      RMIManagedConnectionFactory rMIManagedConnectionFactory0 = new RMIManagedConnectionFactory();
      URI uRI0 = new URI();
      JMXPrincipal jMXPrincipal0 = new JMXPrincipal("G'IDjbvveo(a5N:7wc ");
      Properties properties0 = new Properties("G'IDjbvveo(a5N:7wc ");
      RMIRequestInfo rMIRequestInfo0 = new RMIRequestInfo(uRI0, properties0);
      LinkedList<String> linkedList0 = new LinkedList<String>();
      linkedList0.add("G'IDjbvveo(a5N:7wc ");
      // Undeclared exception!
      try {
        rMIManagedConnectionFactory0.matchManagedConnections((List) linkedList0, (Principal) jMXPrincipal0, (ConnectionRequestInfo) rMIRequestInfo0);
        fail("Expecting exception: ClassCastException");
      } catch(ClassCastException e) {
        /*
         * java.lang.String cannot be cast to org.exolab.jms.net.rmi.RMIManagedConnection
         */
      }
  }

  @Test
  public void test8()  throws Throwable  {
      RMIManagedConnectionFactory rMIManagedConnectionFactory0 = new RMIManagedConnectionFactory();
      LinkedList<String> linkedList0 = new LinkedList<String>();
      ManagedConnectionAcceptor managedConnectionAcceptor0 = rMIManagedConnectionFactory0.matchManagedConnectionAcceptors((List) linkedList0, (ConnectionRequestInfo) null);
      assertNull(managedConnectionAcceptor0);
  }

  @Test
  public void test9()  throws Throwable  {
      RMIManagedConnectionFactory rMIManagedConnectionFactory0 = new RMIManagedConnectionFactory();
      URI uRI0 = new URI();
      RMIRequestInfo rMIRequestInfo0 = new RMIRequestInfo(uRI0);
      LinkedList<Integer> linkedList0 = new LinkedList<Integer>();
      ManagedConnectionAcceptor managedConnectionAcceptor0 = rMIManagedConnectionFactory0.matchManagedConnectionAcceptors((List) linkedList0, (ConnectionRequestInfo) rMIRequestInfo0);
      assertNull(managedConnectionAcceptor0);
  }
}
