/*
 * This file was automatically generated by EvoSuite
 */

package org.exolab.jms.net.connector;

import org.junit.Test;
import org.junit.runner.RunWith;
import org.evosuite.junit.EvoSuiteRunner;
import static org.junit.Assert.*;
import java.io.ByteArrayOutputStream;
import java.io.IOException;
import java.io.ObjectOutput;
import java.io.ObjectOutputStream;
import java.io.OutputStream;
import java.lang.reflect.Method;
import org.exolab.jms.net.connector.Response;
import org.junit.BeforeClass;

@RunWith(EvoSuiteRunner.class)
public class TestResponse {

  @BeforeClass 
  public static void initEvoSuiteFramework(){ 
    org.evosuite.Properties.REPLACE_CALLS = true; 
  } 


  @Test
  public void test0()  throws Throwable  {
      Response response0 = new Response((Object) "zh", (Method) null);
      assertEquals(true, response0.isReturn());
  }

  @Test
  public void test1()  throws Throwable  {
      Response response0 = new Response((Throwable) null);
      Object object0 = response0.getObject();
      assertNull(object0);
  }

  @Test
  public void test2()  throws Throwable  {
      Response response0 = new Response((Throwable) null);
      ByteArrayOutputStream byteArrayOutputStream0 = new ByteArrayOutputStream();
      ObjectOutputStream objectOutputStream0 = new ObjectOutputStream((OutputStream) byteArrayOutputStream0);
      // Undeclared exception!
      try {
        response0.write((ObjectOutput) objectOutputStream0);
        fail("Expecting exception: NullPointerException");
      } catch(NullPointerException e) {
      }
  }

  @Test
  public void test3()  throws Throwable  {
      Response response0 = new Response((Throwable) null);
      boolean boolean0 = response0.isException();
      assertEquals(false, boolean0);
  }
}
