/*
 * This file was automatically generated by EvoSuite
 */

package org.exolab.jms.tranlog;

import org.junit.Test;
import org.junit.runner.RunWith;
import org.evosuite.junit.EvoSuiteRunner;
import static org.junit.Assert.*;
import java.io.ByteArrayOutputStream;
import java.io.FilterOutputStream;
import java.io.IOException;
import java.io.ObjectOutput;
import java.io.ObjectOutputStream;
import java.io.OutputStream;
import org.evosuite.runtime.System;
import org.exolab.jms.tranlog.DataTransactionLogEntry;
import org.exolab.jms.tranlog.ExternalXid;
import org.exolab.jms.tranlog.StateTransactionLogEntry;
import org.junit.BeforeClass;

@RunWith(EvoSuiteRunner.class)
public class TestBaseTransactionLogEntry {

  @BeforeClass 
  public static void initEvoSuiteFramework(){ 
    org.evosuite.Properties.REPLACE_CALLS = true; 
  } 


  @Test
  public void test0()  throws Throwable  {
      DataTransactionLogEntry dataTransactionLogEntry0 = new DataTransactionLogEntry();
      boolean boolean0 = dataTransactionLogEntry0.transactionExpired();
      assertEquals(false, boolean0);
      assertEquals((-1L), dataTransactionLogEntry0.getCreated());
      assertEquals(0L, dataTransactionLogEntry0.getExpiryTime());
  }

  @Test
  public void test1()  throws Throwable  {
      ExternalXid externalXid0 = new ExternalXid();
      DataTransactionLogEntry dataTransactionLogEntry0 = new DataTransactionLogEntry(externalXid0, "");
      long long0 = dataTransactionLogEntry0.getExpiryTime();
      assertEquals(0L, long0);
      assertEquals(0L, dataTransactionLogEntry0.getCreated());
  }

  @Test
  public void test2()  throws Throwable  {
      byte[] byteArray0 = new byte[2];
      ExternalXid externalXid0 = new ExternalXid((-761), byteArray0, byteArray0);
      StateTransactionLogEntry stateTransactionLogEntry0 = new StateTransactionLogEntry(externalXid0, "kt7", (-1L));
      ExternalXid externalXid1 = stateTransactionLogEntry0.getExternalXid();
      assertNotNull(externalXid1);
      assertEquals(0L, stateTransactionLogEntry0.getExpiryTime());
      assertEquals(false, stateTransactionLogEntry0.isValid());
      assertEquals(false, stateTransactionLogEntry0.transactionExpired());
  }

  @Test
  public void test3()  throws Throwable  {
      StateTransactionLogEntry stateTransactionLogEntry0 = new StateTransactionLogEntry();
      long long0 = stateTransactionLogEntry0.getCreated();
      assertEquals(0L, stateTransactionLogEntry0.getExpiryTime());
      assertEquals((-1L), long0);
  }

  @Test
  public void test4()  throws Throwable  {
      StateTransactionLogEntry stateTransactionLogEntry0 = new StateTransactionLogEntry();
      stateTransactionLogEntry0.setCreated((-1L));
      assertEquals((-1L), stateTransactionLogEntry0.getCreated());
      assertEquals(0L, stateTransactionLogEntry0.getExpiryTime());
  }

  @Test
  public void test5()  throws Throwable  {
      StateTransactionLogEntry stateTransactionLogEntry0 = new StateTransactionLogEntry();
      stateTransactionLogEntry0.getResourceId();
      assertEquals(0L, stateTransactionLogEntry0.getExpiryTime());
      assertEquals((-1L), stateTransactionLogEntry0.getCreated());
  }

  @Test
  public void test6()  throws Throwable  {
      StateTransactionLogEntry stateTransactionLogEntry0 = new StateTransactionLogEntry();
      assertEquals((-1L), stateTransactionLogEntry0.getCreated());
      
      stateTransactionLogEntry0.setCreated();
      assertEquals(0L, stateTransactionLogEntry0.getExpiryTime());
  }

  @Test
  public void test7()  throws Throwable  {
      StateTransactionLogEntry stateTransactionLogEntry0 = new StateTransactionLogEntry();
      stateTransactionLogEntry0.setExpiryTime(4L);
      assertEquals(4L, stateTransactionLogEntry0.getExpiryTime());
      assertEquals(false, stateTransactionLogEntry0.transactionExpired());
  }

  @Test
  public void test8()  throws Throwable  {
      StateTransactionLogEntry stateTransactionLogEntry0 = new StateTransactionLogEntry();
      stateTransactionLogEntry0.setResourceId((String) null);
      assertEquals(0L, stateTransactionLogEntry0.getExpiryTime());
      assertEquals((-1L), stateTransactionLogEntry0.getCreated());
  }

  @Test
  public void test9()  throws Throwable  {
      DataTransactionLogEntry dataTransactionLogEntry0 = new DataTransactionLogEntry((ExternalXid) null, "MgJRg)V}xFt&j+#", 1L);
      dataTransactionLogEntry0.setExternalXid((ExternalXid) null);
      assertEquals(0L, dataTransactionLogEntry0.getExpiryTime());
      assertEquals(1L, dataTransactionLogEntry0.getCreated());
  }

  @Test
  public void test10()  throws Throwable  {
      System.setCurrentTimeMillis(1L);
      DataTransactionLogEntry dataTransactionLogEntry0 = new DataTransactionLogEntry((ExternalXid) null, "MgJRg)V}xFt&j+#", 1L);
      boolean boolean0 = dataTransactionLogEntry0.transactionExpired();
      assertEquals(0L, dataTransactionLogEntry0.getExpiryTime());
      assertEquals(1L, dataTransactionLogEntry0.getCreated());
      assertEquals(true, boolean0);
  }

  @Test
  public void test11()  throws Throwable  {
      StateTransactionLogEntry stateTransactionLogEntry0 = new StateTransactionLogEntry();
      ByteArrayOutputStream byteArrayOutputStream0 = new ByteArrayOutputStream();
      FilterOutputStream filterOutputStream0 = new FilterOutputStream((OutputStream) byteArrayOutputStream0);
      ObjectOutputStream objectOutputStream0 = new ObjectOutputStream((OutputStream) filterOutputStream0);
      try {
        stateTransactionLogEntry0.writeExternal((ObjectOutput) objectOutputStream0);
        fail("Expecting exception: IOException");
      } catch(IOException e) {
        /*
         * writeExternal : entry has invalid state
         */
      }
  }

  @Test
  public void test12()  throws Throwable  {
      ExternalXid externalXid0 = new ExternalXid();
      DataTransactionLogEntry dataTransactionLogEntry0 = new DataTransactionLogEntry(externalXid0, "");
      boolean boolean0 = dataTransactionLogEntry0.isValid();
      assertEquals(0L, dataTransactionLogEntry0.getCreated());
      assertEquals(true, boolean0);
      assertEquals(0L, dataTransactionLogEntry0.getExpiryTime());
  }

  @Test
  public void test13()  throws Throwable  {
      byte[] byteArray0 = new byte[2];
      System.setCurrentTimeMillis((-1L));
      ExternalXid externalXid0 = new ExternalXid((-761), byteArray0, byteArray0);
      DataTransactionLogEntry dataTransactionLogEntry0 = new DataTransactionLogEntry(externalXid0, "kt7");
      ByteArrayOutputStream byteArrayOutputStream0 = new ByteArrayOutputStream();
      ObjectOutputStream objectOutputStream0 = new ObjectOutputStream((OutputStream) byteArrayOutputStream0);
      try {
        dataTransactionLogEntry0.writeExternal((ObjectOutput) objectOutputStream0);
        fail("Expecting exception: IOException");
      } catch(IOException e) {
        /*
         * writeExternal : entry has invalid state
         */
      }
  }
}
