/*
 * This file was automatically generated by EvoSuite
 */

package org.exolab.jms.tools.migration.proxy;

import org.junit.Test;
import org.junit.runner.RunWith;
import org.evosuite.junit.EvoSuiteRunner;
import static org.junit.Assert.*;
import java.sql.Connection;
import java.util.Iterator;
import java.util.LinkedList;
import java.util.Vector;
import javax.jms.JMSException;
import org.apache.derby.impl.sql.execute.rts.RealHashLeftOuterJoinStatistics;
import org.apache.derby.impl.sql.execute.rts.ResultSetStatistics;
import org.exolab.jms.authentication.User;
import org.exolab.jms.persistence.PersistenceException;
import org.exolab.jms.tools.migration.IteratorAdapter;
import org.exolab.jms.tools.migration.StoreIterator;
import org.exolab.jms.tools.migration.proxy.UserStore;
import org.junit.BeforeClass;

@RunWith(EvoSuiteRunner.class)
public class TestUserStore {

  @BeforeClass 
  public static void initEvoSuiteFramework(){ 
    org.evosuite.Properties.REPLACE_CALLS = true; 
  } 


  @Test
  public void test0()  throws Throwable  {
      UserStore userStore0 = new UserStore((Connection) null);
      // Undeclared exception!
      try {
        userStore0.size();
        fail("Expecting exception: NullPointerException");
      } catch(NullPointerException e) {
      }
  }

  @Test
  public void test1()  throws Throwable  {
      UserStore userStore0 = new UserStore((Connection) null);
      // Undeclared exception!
      try {
        userStore0.exportCollection();
        fail("Expecting exception: NullPointerException");
      } catch(NullPointerException e) {
      }
  }

  @Test
  public void test2()  throws Throwable  {
      UserStore userStore0 = new UserStore((Connection) null);
      RealHashLeftOuterJoinStatistics realHashLeftOuterJoinStatistics0 = new RealHashLeftOuterJoinStatistics((-1155), (-1155), (-1155), (long) (-1155), (long) (-1155), (long) (-1155), (long) (-1155), (-1155), (-1155), (-1155), (-1155), (long) (-1155), (double) (-1155), (double) (-1155), (ResultSetStatistics) null, (ResultSetStatistics) null, (-1155));
      Vector<Object> vector0 = realHashLeftOuterJoinStatistics0.getChildren();
      Iterator<String> iterator0 = vector0.iterator();
      IteratorAdapter iteratorAdapter0 = new IteratorAdapter(iterator0);
      // Undeclared exception!
      try {
        userStore0.importCollection((StoreIterator) iteratorAdapter0);
        fail("Expecting exception: NullPointerException");
      } catch(NullPointerException e) {
      }
  }

  @Test
  public void test3()  throws Throwable  {
      UserStore userStore0 = new UserStore((Connection) null);
      LinkedList<User> linkedList0 = new LinkedList<User>();
      Iterator<User> iterator0 = linkedList0.iterator();
      IteratorAdapter iteratorAdapter0 = new IteratorAdapter(iterator0);
      userStore0.importCollection((StoreIterator) iteratorAdapter0);
      assertEquals(false, iteratorAdapter0.hasNext());
  }
}
