/*
 * This file was automatically generated by EvoSuite
 */

package org.exolab.jms.tools.migration.proxy;

import org.junit.Test;
import org.junit.runner.RunWith;
import org.evosuite.junit.EvoSuiteRunner;
import static org.junit.Assert.*;
import java.sql.Connection;
import java.util.Iterator;
import java.util.Vector;
import javax.jms.JMSException;
import org.apache.derby.impl.sql.compile.CollectNodesVisitor;
import org.exolab.jms.client.JmsDestination;
import org.exolab.jms.client.JmsQueue;
import org.exolab.jms.persistence.PersistenceException;
import org.exolab.jms.tools.migration.IteratorAdapter;
import org.exolab.jms.tools.migration.StoreIterator;
import org.exolab.jms.tools.migration.proxy.Consumer;
import org.exolab.jms.tools.migration.proxy.ConsumerStore;
import org.exolab.jms.tools.migration.proxy.DestinationStore;
import org.exolab.jms.tools.migration.proxy.Subscription;
import org.junit.BeforeClass;

@RunWith(EvoSuiteRunner.class)
public class TestConsumerStore {

  @BeforeClass 
  public static void initEvoSuiteFramework(){ 
    org.evosuite.Properties.REPLACE_CALLS = true; 
  } 


  @Test
  public void test0()  throws Throwable  {
      ConsumerStore consumerStore0 = new ConsumerStore((DestinationStore) null, (Connection) null);
      // Undeclared exception!
      try {
        consumerStore0.size();
        fail("Expecting exception: NullPointerException");
      } catch(NullPointerException e) {
      }
  }

  @Test
  public void test1()  throws Throwable  {
      ConsumerStore consumerStore0 = new ConsumerStore((DestinationStore) null, (Connection) null);
      // Undeclared exception!
      try {
        consumerStore0.exportCollection();
        fail("Expecting exception: NullPointerException");
      } catch(NullPointerException e) {
      }
  }

  @Test
  public void test2()  throws Throwable  {
      ConsumerStore consumerStore0 = new ConsumerStore((DestinationStore) null, (Connection) null);
      Class<?> class0 = ConsumerStore.class;
      CollectNodesVisitor collectNodesVisitor0 = new CollectNodesVisitor(class0, class0);
      Vector<Object> vector0 = collectNodesVisitor0.getList();
      Iterator<String> iterator0 = vector0.iterator();
      IteratorAdapter iteratorAdapter0 = new IteratorAdapter(iterator0);
      consumerStore0.importCollection((StoreIterator) iteratorAdapter0);
      assertEquals(false, iteratorAdapter0.hasNext());
  }

  @Test
  public void test3()  throws Throwable  {
      ConsumerStore consumerStore0 = new ConsumerStore((DestinationStore) null, (Connection) null);
      JmsQueue jmsQueue0 = new JmsQueue();
      Consumer consumer0 = new Consumer(jmsQueue0);
      consumerStore0.addSubscriptions((-1475L), consumer0);
      assertNull(consumer0.getClientID());
  }

  @Test
  public void test4()  throws Throwable  {
      ConsumerStore consumerStore0 = new ConsumerStore((DestinationStore) null, (Connection) null);
      JmsQueue jmsQueue0 = new JmsQueue();
      Subscription subscription0 = new Subscription((JmsDestination) jmsQueue0);
      consumerStore0.addMessages((-1475L), (-1475L), subscription0);
  }
}
