/*
 * This file was automatically generated by EvoSuite
 */

package org.exolab.jms.server.net;

import org.junit.Test;
import org.junit.runner.RunWith;
import org.evosuite.junit.EvoSuiteRunner;
import static org.junit.Assert.*;
import java.rmi.server.ObjID;
import javax.jms.JMSException;
import org.exolab.jms.net.orb.UnicastDelegate;
import org.exolab.jms.net.proxy.Delegate;
import org.exolab.jms.server.net.RemoteServerConnectionFactory__Proxy;
import org.junit.BeforeClass;

@RunWith(EvoSuiteRunner.class)
public class TestRemoteServerConnectionFactory__Proxy {

  @BeforeClass 
  public static void initEvoSuiteFramework(){ 
    org.evosuite.Properties.REPLACE_CALLS = true; 
  } 


  @Test
  public void test0()  throws Throwable  {
      ObjID objID0 = new ObjID();
      UnicastDelegate unicastDelegate0 = new UnicastDelegate(objID0, "");
      RemoteServerConnectionFactory__Proxy remoteServerConnectionFactory__Proxy0 = new RemoteServerConnectionFactory__Proxy((Delegate) unicastDelegate0);
      try {
        remoteServerConnectionFactory__Proxy0.createConnection("", "", "");
        fail("Expecting exception: JMSException");
      } catch(JMSException e) {
        /*
         * Argument base is null and argument uriSpec is null or an empty string
         */
      }
  }
}
