/*
 * This file was automatically generated by EvoSuite
 */

package org.exolab.jms.messagemgr;

import org.junit.Test;
import org.junit.runner.RunWith;
import org.evosuite.junit.EvoSuiteRunner;
import static org.junit.Assert.*;
import org.exolab.jms.client.JmsDestination;
import org.exolab.jms.client.JmsQueue;
import org.exolab.jms.client.JmsTopic;
import org.exolab.jms.messagemgr.MessageHandleComparator;
import org.exolab.jms.messagemgr.PersistentMessageHandle;
import org.junit.BeforeClass;

@RunWith(EvoSuiteRunner.class)
public class TestMessageHandleComparator {

  @BeforeClass 
  public static void initEvoSuiteFramework(){ 
    org.evosuite.Properties.REPLACE_CALLS = true; 
  } 


  @Test
  public void test0()  throws Throwable  {
      MessageHandleComparator messageHandleComparator0 = new MessageHandleComparator();
      int int0 = messageHandleComparator0.compare((Object) messageHandleComparator0, (Object) messageHandleComparator0);
      assertEquals((-1), int0);
  }

  @Test
  public void test1()  throws Throwable  {
      MessageHandleComparator messageHandleComparator0 = new MessageHandleComparator();
      JmsQueue jmsQueue0 = new JmsQueue("");
      PersistentMessageHandle persistentMessageHandle0 = new PersistentMessageHandle("", (-1923), (-1L), (long) (-1923), (-1L), (JmsDestination) jmsQueue0);
      int int0 = messageHandleComparator0.compare((Object) persistentMessageHandle0, (Object) persistentMessageHandle0);
      assertEquals(0, int0);
  }

  @Test
  public void test2()  throws Throwable  {
      MessageHandleComparator messageHandleComparator0 = new MessageHandleComparator();
      JmsTopic jmsTopic0 = new JmsTopic("*");
      PersistentMessageHandle persistentMessageHandle0 = new PersistentMessageHandle("*", (-1), (long) (-1), (long) (-1), (long) (-1), (JmsDestination) jmsTopic0);
      int int0 = messageHandleComparator0.compare((Object) persistentMessageHandle0, (Object) "*");
      assertEquals((-1), int0);
  }

  @Test
  public void test3()  throws Throwable  {
      MessageHandleComparator messageHandleComparator0 = new MessageHandleComparator();
      JmsQueue jmsQueue0 = new JmsQueue("");
      PersistentMessageHandle persistentMessageHandle0 = new PersistentMessageHandle("", 0, (-1L), (long) 0, (-1L), (JmsDestination) jmsQueue0);
      PersistentMessageHandle persistentMessageHandle1 = new PersistentMessageHandle("", 43, (-1L), (long) 0, (long) 0, (JmsDestination) jmsQueue0, "");
      int int0 = messageHandleComparator0.compare((Object) persistentMessageHandle0, (Object) persistentMessageHandle1);
      assertEquals(1, int0);
  }

  @Test
  public void test4()  throws Throwable  {
      MessageHandleComparator messageHandleComparator0 = new MessageHandleComparator();
      JmsQueue jmsQueue0 = new JmsQueue("");
      PersistentMessageHandle persistentMessageHandle0 = new PersistentMessageHandle("", (-1923), (-1L), (long) (-1923), (-1L), (JmsDestination) jmsQueue0);
      PersistentMessageHandle persistentMessageHandle1 = new PersistentMessageHandle("", (-1923), (long) (-1923), (long) (-1923), (long) (-1923), (JmsDestination) jmsQueue0, "");
      int int0 = messageHandleComparator0.compare((Object) persistentMessageHandle0, (Object) persistentMessageHandle1);
      assertEquals(1, int0);
  }

  @Test
  public void test5()  throws Throwable  {
      MessageHandleComparator messageHandleComparator0 = new MessageHandleComparator();
      JmsQueue jmsQueue0 = new JmsQueue("");
      PersistentMessageHandle persistentMessageHandle0 = new PersistentMessageHandle("", (-1923), (-1L), (long) (-1923), (-1L), (JmsDestination) jmsQueue0);
      PersistentMessageHandle persistentMessageHandle1 = new PersistentMessageHandle("", (-1923), (long) (-1923), (long) (-1923), (long) (-1923), (JmsDestination) jmsQueue0, "");
      int int0 = messageHandleComparator0.compare((Object) persistentMessageHandle1, (Object) persistentMessageHandle0);
      assertEquals((-1), int0);
  }

  @Test
  public void test6()  throws Throwable  {
      MessageHandleComparator messageHandleComparator0 = new MessageHandleComparator();
      boolean boolean0 = messageHandleComparator0.equals((Object) "*");
      assertEquals(false, boolean0);
  }

  @Test
  public void test7()  throws Throwable  {
      MessageHandleComparator messageHandleComparator0 = new MessageHandleComparator();
      boolean boolean0 = messageHandleComparator0.equals((Object) messageHandleComparator0);
      assertEquals(true, boolean0);
  }
}
