/*
 * This file was automatically generated by EvoSuite
 */

package org.exolab.jms.messagemgr;

import org.junit.Test;
import org.junit.runner.RunWith;
import org.evosuite.junit.EvoSuiteRunner;
import static org.junit.Assert.*;
import org.exolab.jms.client.JmsDestination;
import org.exolab.jms.client.JmsTemporaryTopic;
import org.exolab.jms.client.JmsTopic;
import org.exolab.jms.messagemgr.MessageHandle;
import org.exolab.jms.messagemgr.MessageQueue;
import org.exolab.jms.messagemgr.PersistentMessageHandle;
import org.junit.BeforeClass;

@RunWith(EvoSuiteRunner.class)
public class TestMessageQueue {

  @BeforeClass 
  public static void initEvoSuiteFramework(){ 
    org.evosuite.Properties.REPLACE_CALLS = true; 
  } 


  @Test
  public void test0()  throws Throwable  {
      MessageQueue messageQueue0 = new MessageQueue();
      boolean boolean0 = messageQueue0.contains((MessageHandle) null);
      assertEquals(false, boolean0);
  }

  @Test
  public void test1()  throws Throwable  {
      MessageQueue messageQueue0 = new MessageQueue();
      messageQueue0.clear();
      assertEquals(0, messageQueue0.size());
  }

  @Test
  public void test2()  throws Throwable  {
      MessageQueue messageQueue0 = new MessageQueue();
      MessageHandle[] messageHandleArray0 = messageQueue0.toArray();
      assertNotNull(messageHandleArray0);
  }

  @Test
  public void test3()  throws Throwable  {
      MessageQueue messageQueue0 = new MessageQueue();
      int int0 = messageQueue0.size();
      assertEquals(0, int0);
  }

  @Test
  public void test4()  throws Throwable  {
      MessageQueue messageQueue0 = new MessageQueue();
      JmsTopic jmsTopic0 = new JmsTopic();
      PersistentMessageHandle persistentMessageHandle0 = new PersistentMessageHandle("", (-632), (long) (-632), (long) (-632), (long) (-632), (JmsDestination) jmsTopic0);
      messageQueue0.add((MessageHandle) persistentMessageHandle0);
      boolean boolean0 = messageQueue0.add((MessageHandle) persistentMessageHandle0);
      assertEquals(1, messageQueue0.size());
      assertEquals(false, boolean0);
  }

  @Test
  public void test5()  throws Throwable  {
      MessageQueue messageQueue0 = new MessageQueue();
      MessageHandle messageHandle0 = messageQueue0.remove((MessageHandle) null);
      assertNull(messageHandle0);
  }

  @Test
  public void test6()  throws Throwable  {
      MessageQueue messageQueue0 = new MessageQueue();
      JmsTemporaryTopic jmsTemporaryTopic0 = new JmsTemporaryTopic();
      PersistentMessageHandle persistentMessageHandle0 = new PersistentMessageHandle("", (-748), (long) 0, (long) 0, 1048576L, (JmsDestination) jmsTemporaryTopic0);
      messageQueue0.add((MessageHandle) persistentMessageHandle0);
      assertEquals(1, messageQueue0.size());
      
      messageQueue0.remove((MessageHandle) persistentMessageHandle0);
      assertEquals(0, messageQueue0.size());
  }

  @Test
  public void test7()  throws Throwable  {
      MessageQueue messageQueue0 = new MessageQueue();
      MessageHandle messageHandle0 = messageQueue0.remove((String) null);
      assertNull(messageHandle0);
  }

  @Test
  public void test8()  throws Throwable  {
      MessageQueue messageQueue0 = new MessageQueue();
      JmsTopic jmsTopic0 = new JmsTopic("");
      PersistentMessageHandle persistentMessageHandle0 = new PersistentMessageHandle("", (-68), (long) (-68), 0L, (-1L), (JmsDestination) jmsTopic0, "");
      messageQueue0.add((MessageHandle) persistentMessageHandle0);
      assertEquals(1, messageQueue0.size());
      
      messageQueue0.remove("");
      assertEquals(0, messageQueue0.size());
  }

  @Test
  public void test9()  throws Throwable  {
      MessageQueue messageQueue0 = new MessageQueue();
      MessageHandle messageHandle0 = messageQueue0.removeFirst();
      assertNull(messageHandle0);
  }

  @Test
  public void test10()  throws Throwable  {
      MessageQueue messageQueue0 = new MessageQueue();
      JmsTopic jmsTopic0 = new JmsTopic();
      PersistentMessageHandle persistentMessageHandle0 = new PersistentMessageHandle("", (-632), (long) (-632), (long) (-632), (long) (-632), (JmsDestination) jmsTopic0);
      messageQueue0.add((MessageHandle) persistentMessageHandle0);
      assertEquals(1, messageQueue0.size());
      
      messageQueue0.removeFirst();
      assertEquals(0, messageQueue0.size());
  }
}
