/*
 * This file was automatically generated by EvoSuite
 */

package org.exolab.jms.messagemgr;

import org.junit.Test;
import org.junit.runner.RunWith;
import org.evosuite.junit.EvoSuiteRunner;
import static org.junit.Assert.*;
import javax.jms.JMSException;
import org.exolab.jms.client.JmsQueue;
import org.exolab.jms.config.Configuration;
import org.exolab.jms.lease.LeaseManager;
import org.exolab.jms.messagemgr.QueueDestinationCache;
import org.exolab.jms.persistence.DatabaseService;
import org.exolab.jms.server.ServerConnectionManager;
import org.junit.BeforeClass;

@RunWith(EvoSuiteRunner.class)
public class TestAbstractDestinationCache {

  @BeforeClass 
  public static void initEvoSuiteFramework(){ 
    org.evosuite.Properties.REPLACE_CALLS = true; 
  } 


  @Test
  public void test0()  throws Throwable  {
      Configuration configuration0 = new Configuration();
      DatabaseService databaseService0 = new DatabaseService(configuration0);
      String string0 = "RsmW\\uj";
      JmsQueue jmsQueue0 = new JmsQueue(string0);
      LeaseManager leaseManager0 = null;
      ServerConnectionManager serverConnectionManager0 = null;
      QueueDestinationCache queueDestinationCache0 = null;
      try {
        queueDestinationCache0 = new QueueDestinationCache(jmsQueue0, databaseService0, leaseManager0, serverConnectionManager0);
        fail("Expecting exception: IllegalArgumentException");
      } catch(IllegalArgumentException e) {
        /*
         * Argument 'leases' is null
         */
      }
  }

  @Test
  public void test1()  throws Throwable  {
      JmsQueue jmsQueue0 = new JmsQueue("");
      LeaseManager leaseManager0 = new LeaseManager();
      QueueDestinationCache queueDestinationCache0 = null;
      try {
        queueDestinationCache0 = new QueueDestinationCache(jmsQueue0, (DatabaseService) null, leaseManager0, (ServerConnectionManager) null);
        fail("Expecting exception: IllegalArgumentException");
      } catch(IllegalArgumentException e) {
        /*
         * Argument 'database' is null
         */
      }
  }

  @Test
  public void test2()  throws Throwable  {
      JmsQueue jmsQueue0 = new JmsQueue();
      Configuration configuration0 = new Configuration();
      DatabaseService databaseService0 = new DatabaseService(configuration0);
      LeaseManager leaseManager0 = new LeaseManager();
      QueueDestinationCache queueDestinationCache0 = null;
      try {
        queueDestinationCache0 = new QueueDestinationCache(jmsQueue0, databaseService0, leaseManager0, (ServerConnectionManager) null);
        fail("Expecting exception: IllegalArgumentException");
      } catch(IllegalArgumentException e) {
        /*
         * Argument 'connections' is null
         */
      }
  }
}
