/*
 * This file was automatically generated by EvoSuite
 */

package org.exolab.jms.config;

import org.junit.Test;
import org.junit.runner.RunWith;
import org.evosuite.junit.EvoSuiteRunner;
import static org.junit.Assert.*;
import java.io.BufferedReader;
import java.io.IOException;
import java.io.PipedReader;
import java.io.PipedWriter;
import java.io.Reader;
import java.io.Writer;
import org.exolab.castor.util.NestedIOException;
import org.exolab.castor.xml.MarshalException;
import org.exolab.castor.xml.ValidationException;
import org.exolab.jms.config.ServerConfiguration;
import org.junit.BeforeClass;
import org.xml.sax.ContentHandler;
import org.xml.sax.ext.DefaultHandler2;

@RunWith(EvoSuiteRunner.class)
public class TestServerConfiguration {

  @BeforeClass 
  public static void initEvoSuiteFramework(){ 
    org.evosuite.Properties.REPLACE_CALLS = true; 
  } 


  @Test
  public void test0()  throws Throwable  {
      ServerConfiguration serverConfiguration0 = new ServerConfiguration();
      serverConfiguration0.setEmbeddedJNDI(true);
      boolean boolean0 = serverConfiguration0.isValid();
      assertEquals(true, serverConfiguration0.hasEmbeddedJNDI());
      assertEquals(true, boolean0);
  }

  @Test
  public void test1()  throws Throwable  {
      ServerConfiguration serverConfiguration0 = new ServerConfiguration();
      serverConfiguration0.deleteEmbeddedJNDI();
      assertEquals(false, serverConfiguration0.hasEmbeddedJNDI());
      assertEquals("localhost", serverConfiguration0.getHost());
      assertEquals(100, serverConfiguration0.getMaxThreads());
      assertEquals(true, serverConfiguration0.getEmbeddedJNDI());
  }

  @Test
  public void test2()  throws Throwable  {
      ServerConfiguration serverConfiguration0 = new ServerConfiguration();
      PipedWriter pipedWriter0 = new PipedWriter();
      try {
        serverConfiguration0.marshal((Writer) pipedWriter0);
        fail("Expecting exception: MarshalException");
      } catch(MarshalException e) {
        /*
         * Pipe not connected
         */
      }
  }

  @Test
  public void test3()  throws Throwable  {
      ServerConfiguration serverConfiguration0 = new ServerConfiguration();
      serverConfiguration0.deleteMaxThreads();
      assertEquals(100, serverConfiguration0.getMaxThreads());
      assertEquals("localhost", serverConfiguration0.getHost());
      assertEquals(true, serverConfiguration0.getEmbeddedJNDI());
      assertEquals(false, serverConfiguration0.hasMaxThreads());
  }

  @Test
  public void test4()  throws Throwable  {
      ServerConfiguration serverConfiguration0 = new ServerConfiguration();
      serverConfiguration0.setMaxThreads(525);
      boolean boolean0 = serverConfiguration0.isValid();
      assertEquals(true, serverConfiguration0.hasMaxThreads());
      assertEquals(true, boolean0);
  }

  @Test
  public void test5()  throws Throwable  {
      ServerConfiguration serverConfiguration0 = new ServerConfiguration();
      DefaultHandler2 defaultHandler2_0 = new DefaultHandler2();
      try {
        serverConfiguration0.marshal((ContentHandler) defaultHandler2_0);
        fail("Expecting exception: NestedIOException");
      } catch(NestedIOException e) {
        /*
         * System property org.xml.sax.parser not specified
         */
      }
  }

  @Test
  public void test6()  throws Throwable  {
      PipedReader pipedReader0 = new PipedReader();
      BufferedReader bufferedReader0 = new BufferedReader((Reader) pipedReader0);
      try {
        ServerConfiguration.unmarshal((Reader) bufferedReader0);
        fail("Expecting exception: MarshalException");
      } catch(MarshalException e) {
        /*
         * Pipe not connected
         */
      }
  }
}
