/*
 * This file was automatically generated by EvoSuite
 */

package org.exolab.jms.config;

import org.junit.Test;
import org.junit.runner.RunWith;
import org.evosuite.junit.EvoSuiteRunner;
import static org.junit.Assert.*;
import java.io.IOException;
import java.io.PipedWriter;
import java.io.Reader;
import java.io.Writer;
import org.exolab.castor.xml.MarshalException;
import org.exolab.castor.xml.ValidationException;
import org.exolab.jms.config.LoggerConfiguration;
import org.junit.BeforeClass;
import org.xml.sax.ContentHandler;

@RunWith(EvoSuiteRunner.class)
public class TestLoggerConfiguration {

  @BeforeClass 
  public static void initEvoSuiteFramework(){ 
    org.evosuite.Properties.REPLACE_CALLS = true; 
  } 


  @Test
  public void test0()  throws Throwable  {
      PipedWriter pipedWriter0 = new PipedWriter();
      LoggerConfiguration loggerConfiguration0 = new LoggerConfiguration();
      try {
        loggerConfiguration0.marshal((Writer) pipedWriter0);
        fail("Expecting exception: ValidationException");
      } catch(ValidationException e) {
        /*
         * file is a required field.
         */
      }
  }

  @Test
  public void test1()  throws Throwable  {
      LoggerConfiguration loggerConfiguration0 = new LoggerConfiguration();
      boolean boolean0 = loggerConfiguration0.isValid();
      assertEquals(false, boolean0);
  }

  @Test
  public void test2()  throws Throwable  {
      LoggerConfiguration loggerConfiguration0 = new LoggerConfiguration();
      loggerConfiguration0.setFile("");
      assertEquals("", loggerConfiguration0.getFile());
  }

  @Test
  public void test3()  throws Throwable  {
      LoggerConfiguration loggerConfiguration0 = new LoggerConfiguration();
      // Undeclared exception!
      try {
        loggerConfiguration0.marshal((ContentHandler) null);
        fail("Expecting exception: IllegalArgumentException");
      } catch(IllegalArgumentException e) {
        /*
         * Argument 'handler' is null.
         */
      }
  }

  @Test
  public void test4()  throws Throwable  {
      try {
        LoggerConfiguration.unmarshal((Reader) null);
        fail("Expecting exception: MarshalException");
      } catch(MarshalException e) {
        /*
         * 
         */
      }
  }
}
