/*
 * This file was automatically generated by EvoSuite
 */

package org.exolab.jms.config;

import org.junit.Test;
import org.junit.runner.RunWith;
import org.evosuite.junit.EvoSuiteRunner;
import static org.junit.Assert.*;
import org.exolab.jms.config.RdbmsDatabaseConfigurationDescriptor;
import org.junit.BeforeClass;

@RunWith(EvoSuiteRunner.class)
public class TestRdbmsDatabaseConfigurationDescriptor {

  @BeforeClass 
  public static void initEvoSuiteFramework(){ 
    org.evosuite.Properties.REPLACE_CALLS = true; 
  } 


  @Test
  public void test0()  throws Throwable  {
      RdbmsDatabaseConfigurationDescriptor rdbmsDatabaseConfigurationDescriptor0 = new RdbmsDatabaseConfigurationDescriptor();
      rdbmsDatabaseConfigurationDescriptor0.getNameSpacePrefix();
      assertEquals("http://openjms.exolab.org/configuration", rdbmsDatabaseConfigurationDescriptor0.getNameSpaceURI());
      assertEquals("RdbmsDatabaseConfiguration", rdbmsDatabaseConfigurationDescriptor0.getXMLName());
  }

  @Test
  public void test1()  throws Throwable  {
      RdbmsDatabaseConfigurationDescriptor rdbmsDatabaseConfigurationDescriptor0 = new RdbmsDatabaseConfigurationDescriptor();
      assertNotNull(rdbmsDatabaseConfigurationDescriptor0);
      
      RdbmsDatabaseConfigurationDescriptor rdbmsDatabaseConfigurationDescriptor1 = (RdbmsDatabaseConfigurationDescriptor)rdbmsDatabaseConfigurationDescriptor0.getValidator();
      assertEquals("http://openjms.exolab.org/configuration", rdbmsDatabaseConfigurationDescriptor0.getNameSpaceURI());
      assertEquals("RdbmsDatabaseConfiguration", rdbmsDatabaseConfigurationDescriptor0.getXMLName());
      assertEquals("http://openjms.exolab.org/configuration", rdbmsDatabaseConfigurationDescriptor1.getNameSpaceURI());
  }

  @Test
  public void test2()  throws Throwable  {
      RdbmsDatabaseConfigurationDescriptor rdbmsDatabaseConfigurationDescriptor0 = new RdbmsDatabaseConfigurationDescriptor();
      assertNotNull(rdbmsDatabaseConfigurationDescriptor0);
      
      String string0 = rdbmsDatabaseConfigurationDescriptor0.getXMLName();
      assertEquals("http://openjms.exolab.org/configuration", rdbmsDatabaseConfigurationDescriptor0.getNameSpaceURI());
      assertEquals("RdbmsDatabaseConfiguration", string0);
      assertNotNull(string0);
  }

  @Test
  public void test3()  throws Throwable  {
      RdbmsDatabaseConfigurationDescriptor rdbmsDatabaseConfigurationDescriptor0 = new RdbmsDatabaseConfigurationDescriptor();
      assertNotNull(rdbmsDatabaseConfigurationDescriptor0);
      
      rdbmsDatabaseConfigurationDescriptor0.getIdentity();
      assertEquals("RdbmsDatabaseConfiguration", rdbmsDatabaseConfigurationDescriptor0.getXMLName());
      assertEquals("http://openjms.exolab.org/configuration", rdbmsDatabaseConfigurationDescriptor0.getNameSpaceURI());
  }

  @Test
  public void test4()  throws Throwable  {
      RdbmsDatabaseConfigurationDescriptor rdbmsDatabaseConfigurationDescriptor0 = new RdbmsDatabaseConfigurationDescriptor();
      assertNotNull(rdbmsDatabaseConfigurationDescriptor0);
      
      rdbmsDatabaseConfigurationDescriptor0.getExtends();
      assertEquals("http://openjms.exolab.org/configuration", rdbmsDatabaseConfigurationDescriptor0.getNameSpaceURI());
      assertEquals("RdbmsDatabaseConfiguration", rdbmsDatabaseConfigurationDescriptor0.getXMLName());
  }

  @Test
  public void test5()  throws Throwable  {
      RdbmsDatabaseConfigurationDescriptor rdbmsDatabaseConfigurationDescriptor0 = new RdbmsDatabaseConfigurationDescriptor();
      assertNotNull(rdbmsDatabaseConfigurationDescriptor0);
      
      rdbmsDatabaseConfigurationDescriptor0.getAccessMode();
      assertEquals("RdbmsDatabaseConfiguration", rdbmsDatabaseConfigurationDescriptor0.getXMLName());
      assertEquals("http://openjms.exolab.org/configuration", rdbmsDatabaseConfigurationDescriptor0.getNameSpaceURI());
  }

  @Test
  public void test6()  throws Throwable  {
      RdbmsDatabaseConfigurationDescriptor rdbmsDatabaseConfigurationDescriptor0 = new RdbmsDatabaseConfigurationDescriptor();
      assertNotNull(rdbmsDatabaseConfigurationDescriptor0);
      
      String string0 = rdbmsDatabaseConfigurationDescriptor0.getNameSpaceURI();
      assertEquals("RdbmsDatabaseConfiguration", rdbmsDatabaseConfigurationDescriptor0.getXMLName());
      assertEquals("http://openjms.exolab.org/configuration", string0);
      assertNotNull(string0);
  }

  @Test
  public void test7()  throws Throwable  {
      RdbmsDatabaseConfigurationDescriptor rdbmsDatabaseConfigurationDescriptor0 = new RdbmsDatabaseConfigurationDescriptor();
      assertNotNull(rdbmsDatabaseConfigurationDescriptor0);
      
      rdbmsDatabaseConfigurationDescriptor0.getJavaClass();
      assertEquals("http://openjms.exolab.org/configuration", rdbmsDatabaseConfigurationDescriptor0.getNameSpaceURI());
      assertEquals("RdbmsDatabaseConfiguration", rdbmsDatabaseConfigurationDescriptor0.getXMLName());
  }
}
