/*
 * This file was automatically generated by EvoSuite
 */

package org.exolab.jms.config;

import org.junit.Test;
import org.junit.runner.RunWith;
import org.evosuite.junit.EvoSuiteRunner;
import static org.junit.Assert.*;
import java.io.IOException;
import java.io.Reader;
import java.io.Writer;
import org.exolab.castor.util.NestedIOException;
import org.exolab.castor.xml.MarshalException;
import org.exolab.castor.xml.ValidationException;
import org.exolab.jms.config.SecurityConfiguration;
import org.junit.BeforeClass;
import org.xml.sax.ContentHandler;
import org.xml.sax.helpers.DefaultHandler;

@RunWith(EvoSuiteRunner.class)
public class TestSecurityConfiguration {

  @BeforeClass 
  public static void initEvoSuiteFramework(){ 
    org.evosuite.Properties.REPLACE_CALLS = true; 
  } 


  @Test
  public void test0()  throws Throwable  {
      SecurityConfiguration securityConfiguration0 = new SecurityConfiguration();
      boolean boolean0 = securityConfiguration0.isValid();
      assertEquals(true, boolean0);
      assertEquals(false, securityConfiguration0.getSecurityEnabled());
  }

  @Test
  public void test1()  throws Throwable  {
      SecurityConfiguration securityConfiguration0 = new SecurityConfiguration();
      boolean boolean0 = securityConfiguration0.getSecurityEnabled();
      assertEquals(false, boolean0);
  }

  @Test
  public void test2()  throws Throwable  {
      SecurityConfiguration securityConfiguration0 = new SecurityConfiguration();
      securityConfiguration0.setSecurityEnabled(false);
      assertEquals(true, securityConfiguration0.hasSecurityEnabled());
  }

  @Test
  public void test3()  throws Throwable  {
      SecurityConfiguration securityConfiguration0 = new SecurityConfiguration();
      DefaultHandler defaultHandler0 = new DefaultHandler();
      try {
        securityConfiguration0.marshal((ContentHandler) defaultHandler0);
        fail("Expecting exception: NestedIOException");
      } catch(NestedIOException e) {
        /*
         * System property org.xml.sax.parser not specified
         */
      }
  }

  @Test
  public void test4()  throws Throwable  {
      SecurityConfiguration securityConfiguration0 = new SecurityConfiguration();
      // Undeclared exception!
      try {
        securityConfiguration0.marshal((Writer) null);
        fail("Expecting exception: IllegalArgumentException");
      } catch(IllegalArgumentException e) {
        /*
         * Argument 'out' is null.
         */
      }
  }

  @Test
  public void test5()  throws Throwable  {
      SecurityConfiguration securityConfiguration0 = new SecurityConfiguration();
      securityConfiguration0.deleteSecurityEnabled();
      assertEquals(false, securityConfiguration0.hasSecurityEnabled());
      assertEquals(false, securityConfiguration0.getSecurityEnabled());
  }

  @Test
  public void test6()  throws Throwable  {
      try {
        SecurityConfiguration.unmarshal((Reader) null);
        fail("Expecting exception: MarshalException");
      } catch(MarshalException e) {
        /*
         * 
         */
      }
  }
}
