/*
 * This file was automatically generated by EvoSuite
 */

package org.exolab.jms.config;

import org.junit.Test;
import org.junit.runner.RunWith;
import org.evosuite.junit.EvoSuiteRunner;
import static org.junit.Assert.*;
import java.io.BufferedReader;
import java.io.CharArrayWriter;
import java.io.IOException;
import java.io.PipedReader;
import java.io.Reader;
import java.io.Writer;
import java.util.Enumeration;
import org.exolab.castor.util.NestedIOException;
import org.exolab.castor.xml.MarshalException;
import org.exolab.castor.xml.ValidationException;
import org.exolab.jms.config.AdministeredTopic;
import org.exolab.jms.config.Subscriber;
import org.junit.BeforeClass;
import org.xml.sax.ContentHandler;
import org.xml.sax.ext.DefaultHandler2;

@RunWith(EvoSuiteRunner.class)
public class TestAdministeredTopic {

  @BeforeClass 
  public static void initEvoSuiteFramework(){ 
    org.evosuite.Properties.REPLACE_CALLS = true; 
  } 


  @Test
  public void test0()  throws Throwable  {
      AdministeredTopic administeredTopic0 = new AdministeredTopic();
      Subscriber subscriber0 = new Subscriber();
      boolean boolean0 = administeredTopic0.removeSubscriber(subscriber0);
      assertEquals(false, boolean0);
  }

  @Test
  public void test1()  throws Throwable  {
      AdministeredTopic administeredTopic0 = new AdministeredTopic();
      DefaultHandler2 defaultHandler2_0 = new DefaultHandler2();
      try {
        administeredTopic0.marshal((ContentHandler) defaultHandler2_0);
        fail("Expecting exception: NestedIOException");
      } catch(NestedIOException e) {
        /*
         * System property org.xml.sax.parser not specified
         */
      }
  }

  @Test
  public void test2()  throws Throwable  {
      AdministeredTopic administeredTopic0 = new AdministeredTopic();
      Enumeration<Object> enumeration0 = administeredTopic0.enumerateSubscriber();
      assertEquals(false, enumeration0.hasMoreElements());
  }

  @Test
  public void test3()  throws Throwable  {
      AdministeredTopic administeredTopic0 = new AdministeredTopic();
      Subscriber subscriber0 = new Subscriber();
      administeredTopic0.addSubscriber(subscriber0);
      assertEquals(1, administeredTopic0.getSubscriberCount());
  }

  @Test
  public void test4()  throws Throwable  {
      AdministeredTopic administeredTopic0 = new AdministeredTopic();
      administeredTopic0.clearSubscriber();
      assertEquals(false, administeredTopic0.isValid());
  }

  @Test
  public void test5()  throws Throwable  {
      AdministeredTopic administeredTopic0 = new AdministeredTopic();
      CharArrayWriter charArrayWriter0 = new CharArrayWriter(0);
      try {
        administeredTopic0.marshal((Writer) charArrayWriter0);
        fail("Expecting exception: ValidationException");
      } catch(ValidationException e) {
        /*
         * name is a required field.
         */
      }
  }

  @Test
  public void test6()  throws Throwable  {
      AdministeredTopic administeredTopic0 = new AdministeredTopic();
      Subscriber subscriber0 = new Subscriber();
      administeredTopic0.addSubscriber(0, subscriber0);
      try {
        administeredTopic0.validate();
        fail("Expecting exception: ValidationException");
      } catch(ValidationException e) {
        /*
         * name is a required field.
         */
      }
  }

  @Test
  public void test7()  throws Throwable  {
      AdministeredTopic administeredTopic0 = new AdministeredTopic();
      boolean boolean0 = administeredTopic0.isValid();
      assertEquals(false, boolean0);
  }

  @Test
  public void test8()  throws Throwable  {
      AdministeredTopic administeredTopic0 = new AdministeredTopic();
      administeredTopic0.setName("");
      assertEquals("", administeredTopic0.getName());
  }

  @Test
  public void test9()  throws Throwable  {
      AdministeredTopic administeredTopic0 = new AdministeredTopic();
      int int0 = administeredTopic0.getSubscriberCount();
      assertEquals(0, int0);
  }

  @Test
  public void test10()  throws Throwable  {
      AdministeredTopic administeredTopic0 = new AdministeredTopic();
      try {
        administeredTopic0.getSubscriber((-17));
        fail("Expecting exception: IndexOutOfBoundsException");
      } catch(IndexOutOfBoundsException e) {
      }
  }

  @Test
  public void test11()  throws Throwable  {
      AdministeredTopic administeredTopic0 = new AdministeredTopic();
      try {
        administeredTopic0.getSubscriber(130);
        fail("Expecting exception: IndexOutOfBoundsException");
      } catch(IndexOutOfBoundsException e) {
      }
  }

  @Test
  public void test12()  throws Throwable  {
      AdministeredTopic administeredTopic0 = new AdministeredTopic();
      try {
        administeredTopic0.getSubscriber(0);
        fail("Expecting exception: IndexOutOfBoundsException");
      } catch(IndexOutOfBoundsException e) {
        /*
         * Index: 0, Size: 0
         */
      }
  }

  @Test
  public void test13()  throws Throwable  {
      AdministeredTopic administeredTopic0 = new AdministeredTopic();
      Subscriber subscriber0 = new Subscriber();
      try {
        administeredTopic0.setSubscriber((-1583), subscriber0);
        fail("Expecting exception: IndexOutOfBoundsException");
      } catch(IndexOutOfBoundsException e) {
      }
  }

  @Test
  public void test14()  throws Throwable  {
      AdministeredTopic administeredTopic0 = new AdministeredTopic();
      Subscriber subscriber0 = new Subscriber();
      try {
        administeredTopic0.setSubscriber(0, subscriber0);
        fail("Expecting exception: IndexOutOfBoundsException");
      } catch(IndexOutOfBoundsException e) {
        /*
         * Index: 0, Size: 0
         */
      }
  }

  @Test
  public void test15()  throws Throwable  {
      AdministeredTopic administeredTopic0 = new AdministeredTopic();
      Subscriber subscriber0 = new Subscriber();
      try {
        administeredTopic0.setSubscriber(1448, subscriber0);
        fail("Expecting exception: IndexOutOfBoundsException");
      } catch(IndexOutOfBoundsException e) {
      }
  }

  @Test
  public void test16()  throws Throwable  {
      AdministeredTopic administeredTopic0 = new AdministeredTopic();
      Subscriber[] subscriberArray0 = new Subscriber[6];
      administeredTopic0.setSubscriber(subscriberArray0);
      assertEquals(6, administeredTopic0.getSubscriberCount());
  }

  @Test
  public void test17()  throws Throwable  {
      PipedReader pipedReader0 = new PipedReader();
      BufferedReader bufferedReader0 = new BufferedReader((Reader) pipedReader0, 1373);
      try {
        AdministeredTopic.unmarshal((Reader) bufferedReader0);
        fail("Expecting exception: MarshalException");
      } catch(MarshalException e) {
        /*
         * Pipe not connected
         */
      }
  }
}
