/*
 * This file was automatically generated by EvoSuite
 */

package org.exolab.jms.config;

import org.junit.Test;
import org.junit.runner.RunWith;
import org.evosuite.junit.EvoSuiteRunner;
import static org.junit.Assert.*;
import org.exolab.jms.config.AdministeredTopicDescriptor;
import org.junit.BeforeClass;

@RunWith(EvoSuiteRunner.class)
public class TestAdministeredTopicDescriptor {

  @BeforeClass 
  public static void initEvoSuiteFramework(){ 
    org.evosuite.Properties.REPLACE_CALLS = true; 
  } 


  @Test
  public void test0()  throws Throwable  {
      AdministeredTopicDescriptor administeredTopicDescriptor0 = new AdministeredTopicDescriptor();
      AdministeredTopicDescriptor administeredTopicDescriptor1 = (AdministeredTopicDescriptor)administeredTopicDescriptor0.getValidator();
      assertEquals("AdministeredTopic", administeredTopicDescriptor0.getXMLName());
      assertEquals("AdministeredTopic", administeredTopicDescriptor1.getXMLName());
  }

  @Test
  public void test1()  throws Throwable  {
      AdministeredTopicDescriptor administeredTopicDescriptor0 = new AdministeredTopicDescriptor();
      assertNotNull(administeredTopicDescriptor0);
      
      String string0 = administeredTopicDescriptor0.getXMLName();
      assertEquals("AdministeredTopic", string0);
      assertNotNull(string0);
  }

  @Test
  public void test2()  throws Throwable  {
      AdministeredTopicDescriptor administeredTopicDescriptor0 = new AdministeredTopicDescriptor();
      assertNotNull(administeredTopicDescriptor0);
      
      administeredTopicDescriptor0.getIdentity();
      assertEquals("AdministeredTopic", administeredTopicDescriptor0.getXMLName());
  }

  @Test
  public void test3()  throws Throwable  {
      AdministeredTopicDescriptor administeredTopicDescriptor0 = new AdministeredTopicDescriptor();
      assertNotNull(administeredTopicDescriptor0);
      
      administeredTopicDescriptor0.getAccessMode();
      assertEquals("AdministeredTopic", administeredTopicDescriptor0.getXMLName());
  }

  @Test
  public void test4()  throws Throwable  {
      AdministeredTopicDescriptor administeredTopicDescriptor0 = new AdministeredTopicDescriptor();
      assertNotNull(administeredTopicDescriptor0);
      
      administeredTopicDescriptor0.getNameSpacePrefix();
      assertEquals("AdministeredTopic", administeredTopicDescriptor0.getXMLName());
  }

  @Test
  public void test5()  throws Throwable  {
      AdministeredTopicDescriptor administeredTopicDescriptor0 = new AdministeredTopicDescriptor();
      assertNotNull(administeredTopicDescriptor0);
      
      administeredTopicDescriptor0.getNameSpaceURI();
      assertEquals("AdministeredTopic", administeredTopicDescriptor0.getXMLName());
  }

  @Test
  public void test6()  throws Throwable  {
      AdministeredTopicDescriptor administeredTopicDescriptor0 = new AdministeredTopicDescriptor();
      assertNotNull(administeredTopicDescriptor0);
      
      administeredTopicDescriptor0.getExtends();
      assertEquals("AdministeredTopic", administeredTopicDescriptor0.getXMLName());
  }

  @Test
  public void test7()  throws Throwable  {
      AdministeredTopicDescriptor administeredTopicDescriptor0 = new AdministeredTopicDescriptor();
      assertNotNull(administeredTopicDescriptor0);
      
      administeredTopicDescriptor0.getJavaClass();
      assertEquals("AdministeredTopic", administeredTopicDescriptor0.getXMLName());
  }
}
