/*
 * This file was automatically generated by EvoSuite
 */

package org.exolab.jms.config;

import org.junit.Test;
import org.junit.runner.RunWith;
import org.evosuite.junit.EvoSuiteRunner;
import static org.junit.Assert.*;
import org.exolab.jms.config.XAConnectionFactory;
import org.junit.BeforeClass;

@RunWith(EvoSuiteRunner.class)
public class TestConnectionFactoryType {

  @BeforeClass 
  public static void initEvoSuiteFramework(){ 
    org.evosuite.Properties.REPLACE_CALLS = true; 
  } 


  @Test
  public void test0()  throws Throwable  {
      XAConnectionFactory xAConnectionFactory0 = new XAConnectionFactory();
      xAConnectionFactory0.setName((String) null);
      assertNull(xAConnectionFactory0.getName());
  }

  @Test
  public void test1()  throws Throwable  {
      XAConnectionFactory xAConnectionFactory0 = new XAConnectionFactory();
      String string0 = xAConnectionFactory0.getName();
      assertNull(string0);
  }
}
