/*
 * This file was automatically generated by EvoSuite
 */

package org.exolab.jms.config;

import org.junit.Test;
import org.junit.runner.RunWith;
import org.evosuite.junit.EvoSuiteRunner;
import static org.junit.Assert.*;
import org.exolab.castor.mapping.ClassDescriptor;
import org.exolab.castor.mapping.MappingException;
import org.exolab.castor.xml.NodeType;
import org.exolab.castor.xml.util.XMLClassDescriptorAdapter;
import org.exolab.jms.config.ThreadPriorityDescriptor;
import org.junit.BeforeClass;

@RunWith(EvoSuiteRunner.class)
public class TestThreadPriorityDescriptor {

  @BeforeClass 
  public static void initEvoSuiteFramework(){ 
    org.evosuite.Properties.REPLACE_CALLS = true; 
  } 


  @Test
  public void test0()  throws Throwable  {
      ThreadPriorityDescriptor threadPriorityDescriptor0 = new ThreadPriorityDescriptor();
      threadPriorityDescriptor0.getNameSpacePrefix();
      assertEquals("threadPriority", threadPriorityDescriptor0.getXMLName());
      assertEquals("http://openjms.exolab.org/configuration", threadPriorityDescriptor0.getNameSpaceURI());
  }

  @Test
  public void test1()  throws Throwable  {
      ThreadPriorityDescriptor threadPriorityDescriptor0 = new ThreadPriorityDescriptor();
      threadPriorityDescriptor0.getAccessMode();
      assertEquals("threadPriority", threadPriorityDescriptor0.getXMLName());
      assertEquals("http://openjms.exolab.org/configuration", threadPriorityDescriptor0.getNameSpaceURI());
  }

  @Test
  public void test2()  throws Throwable  {
      ThreadPriorityDescriptor threadPriorityDescriptor0 = new ThreadPriorityDescriptor();
      ThreadPriorityDescriptor threadPriorityDescriptor1 = (ThreadPriorityDescriptor)threadPriorityDescriptor0.getValidator();
      assertEquals("http://openjms.exolab.org/configuration", threadPriorityDescriptor1.getNameSpaceURI());
      assertEquals("threadPriority", threadPriorityDescriptor1.getXMLName());
  }

  @Test
  public void test3()  throws Throwable  {
      ThreadPriorityDescriptor threadPriorityDescriptor0 = new ThreadPriorityDescriptor();
      String string0 = threadPriorityDescriptor0.getNameSpaceURI();
      assertEquals("http://openjms.exolab.org/configuration", string0);
      assertNotNull(string0);
      assertEquals("threadPriority", threadPriorityDescriptor0.getXMLName());
  }

  @Test
  public void test4()  throws Throwable  {
      ThreadPriorityDescriptor threadPriorityDescriptor0 = new ThreadPriorityDescriptor();
      NodeType nodeType0 = NodeType.Text;
      XMLClassDescriptorAdapter xMLClassDescriptorAdapter0 = new XMLClassDescriptorAdapter((ClassDescriptor) threadPriorityDescriptor0, "", nodeType0);
      assertEquals("threadPriority", threadPriorityDescriptor0.getXMLName());
      assertEquals("http://openjms.exolab.org/configuration", threadPriorityDescriptor0.getNameSpaceURI());
  }
}
