/*
 * This file was automatically generated by EvoSuite
 */

package org.exolab.jms.config;

import org.junit.Test;
import org.junit.runner.RunWith;
import org.evosuite.junit.EvoSuiteRunner;
import static org.junit.Assert.*;
import org.exolab.castor.mapping.ClassDescriptor;
import org.exolab.castor.mapping.MappingException;
import org.exolab.castor.xml.util.XMLClassDescriptorAdapter;
import org.exolab.jms.config.SchedulerConfigurationDescriptor;
import org.junit.BeforeClass;

@RunWith(EvoSuiteRunner.class)
public class TestSchedulerConfigurationDescriptor {

  @BeforeClass 
  public static void initEvoSuiteFramework(){ 
    org.evosuite.Properties.REPLACE_CALLS = true; 
  } 


  @Test
  public void test0()  throws Throwable  {
      SchedulerConfigurationDescriptor schedulerConfigurationDescriptor0 = new SchedulerConfigurationDescriptor();
      assertNotNull(schedulerConfigurationDescriptor0);
      
      schedulerConfigurationDescriptor0.getNameSpacePrefix();
      assertEquals("SchedulerConfiguration", schedulerConfigurationDescriptor0.getXMLName());
      assertEquals("http://openjms.exolab.org/configuration", schedulerConfigurationDescriptor0.getNameSpaceURI());
  }

  @Test
  public void test1()  throws Throwable  {
      SchedulerConfigurationDescriptor schedulerConfigurationDescriptor0 = new SchedulerConfigurationDescriptor();
      assertNotNull(schedulerConfigurationDescriptor0);
      
      schedulerConfigurationDescriptor0.getAccessMode();
      assertEquals("SchedulerConfiguration", schedulerConfigurationDescriptor0.getXMLName());
      assertEquals("http://openjms.exolab.org/configuration", schedulerConfigurationDescriptor0.getNameSpaceURI());
  }

  @Test
  public void test2()  throws Throwable  {
      SchedulerConfigurationDescriptor schedulerConfigurationDescriptor0 = new SchedulerConfigurationDescriptor();
      assertNotNull(schedulerConfigurationDescriptor0);
      
      XMLClassDescriptorAdapter xMLClassDescriptorAdapter0 = new XMLClassDescriptorAdapter((ClassDescriptor) schedulerConfigurationDescriptor0, "http://openjms.exolab.org/configuration");
      assertEquals("SchedulerConfiguration", schedulerConfigurationDescriptor0.getXMLName());
      assertEquals("http://openjms.exolab.org/configuration", schedulerConfigurationDescriptor0.getNameSpaceURI());
  }

  @Test
  public void test3()  throws Throwable  {
      SchedulerConfigurationDescriptor schedulerConfigurationDescriptor0 = new SchedulerConfigurationDescriptor();
      assertNotNull(schedulerConfigurationDescriptor0);
      
      String string0 = schedulerConfigurationDescriptor0.getNameSpaceURI();
      assertEquals("SchedulerConfiguration", schedulerConfigurationDescriptor0.getXMLName());
      assertEquals("http://openjms.exolab.org/configuration", string0);
      assertNotNull(string0);
  }

  @Test
  public void test4()  throws Throwable  {
      SchedulerConfigurationDescriptor schedulerConfigurationDescriptor0 = new SchedulerConfigurationDescriptor();
      assertNotNull(schedulerConfigurationDescriptor0);
      
      SchedulerConfigurationDescriptor schedulerConfigurationDescriptor1 = (SchedulerConfigurationDescriptor)schedulerConfigurationDescriptor0.getValidator();
      assertEquals("http://openjms.exolab.org/configuration", schedulerConfigurationDescriptor1.getNameSpaceURI());
      assertEquals("SchedulerConfiguration", schedulerConfigurationDescriptor1.getXMLName());
  }
}
