/*
 * This file was automatically generated by EvoSuite
 */

package org.exolab.jms.config;

import org.junit.Test;
import org.junit.runner.RunWith;
import org.evosuite.junit.EvoSuiteRunner;
import static org.junit.Assert.*;
import org.exolab.castor.mapping.ClassDescriptor;
import org.exolab.castor.mapping.MappingException;
import org.exolab.castor.xml.util.XMLClassDescriptorAdapter;
import org.exolab.jms.config.UsersDescriptor;
import org.junit.BeforeClass;

@RunWith(EvoSuiteRunner.class)
public class TestUsersDescriptor {

  @BeforeClass 
  public static void initEvoSuiteFramework(){ 
    org.evosuite.Properties.REPLACE_CALLS = true; 
  } 


  @Test
  public void test0()  throws Throwable  {
      UsersDescriptor usersDescriptor0 = new UsersDescriptor();
      UsersDescriptor usersDescriptor1 = (UsersDescriptor)usersDescriptor0.getValidator();
      assertEquals("http://openjms.exolab.org/configuration", usersDescriptor1.getNameSpaceURI());
      assertEquals("Users", usersDescriptor1.getXMLName());
  }

  @Test
  public void test1()  throws Throwable  {
      UsersDescriptor usersDescriptor0 = new UsersDescriptor();
      assertNotNull(usersDescriptor0);
      
      XMLClassDescriptorAdapter xMLClassDescriptorAdapter0 = new XMLClassDescriptorAdapter((ClassDescriptor) usersDescriptor0, (String) null);
      assertEquals("http://openjms.exolab.org/configuration", usersDescriptor0.getNameSpaceURI());
      assertEquals("Users", xMLClassDescriptorAdapter0.getXMLName());
  }

  @Test
  public void test2()  throws Throwable  {
      UsersDescriptor usersDescriptor0 = new UsersDescriptor();
      assertNotNull(usersDescriptor0);
      
      usersDescriptor0.getNameSpacePrefix();
      assertEquals("Users", usersDescriptor0.getXMLName());
      assertEquals("http://openjms.exolab.org/configuration", usersDescriptor0.getNameSpaceURI());
  }

  @Test
  public void test3()  throws Throwable  {
      UsersDescriptor usersDescriptor0 = new UsersDescriptor();
      assertNotNull(usersDescriptor0);
      
      usersDescriptor0.getAccessMode();
      assertEquals("Users", usersDescriptor0.getXMLName());
      assertEquals("http://openjms.exolab.org/configuration", usersDescriptor0.getNameSpaceURI());
  }

  @Test
  public void test4()  throws Throwable  {
      UsersDescriptor usersDescriptor0 = new UsersDescriptor();
      assertNotNull(usersDescriptor0);
      
      String string0 = usersDescriptor0.getNameSpaceURI();
      assertEquals("Users", usersDescriptor0.getXMLName());
      assertNotNull(string0);
      assertEquals("http://openjms.exolab.org/configuration", string0);
  }
}
