/*
 * This file was automatically generated by EvoSuite
 */

package org.exolab.jms.config;

import org.junit.Test;
import org.junit.runner.RunWith;
import org.evosuite.junit.EvoSuiteRunner;
import static org.junit.Assert.*;
import org.exolab.jms.config.HttpConfiguration;
import org.exolab.jms.config.HttpsConfiguration;
import org.junit.BeforeClass;

@RunWith(EvoSuiteRunner.class)
public class TestHttpConfigurationType {

  @BeforeClass 
  public static void initEvoSuiteFramework(){ 
    org.evosuite.Properties.REPLACE_CALLS = true; 
  } 


  @Test
  public void test0()  throws Throwable  {
      HttpsConfiguration httpsConfiguration0 = new HttpsConfiguration();
      String string0 = httpsConfiguration0.getServlet();
      assertNotNull(string0);
      assertEquals("localhost", httpsConfiguration0.getWebServerHost());
      assertEquals("/openjms-tunnel/tunnel", string0);
  }

  @Test
  public void test1()  throws Throwable  {
      HttpConfiguration httpConfiguration0 = new HttpConfiguration();
      httpConfiguration0.setWebServerPort(8);
      assertEquals(true, httpConfiguration0.hasWebServerPort());
      assertEquals("localhost", httpConfiguration0.getWebServerHost());
  }

  @Test
  public void test2()  throws Throwable  {
      HttpsConfiguration httpsConfiguration0 = new HttpsConfiguration();
      String string0 = httpsConfiguration0.getWebServerHost();
      assertNotNull(string0);
      assertEquals("/openjms-tunnel/tunnel", httpsConfiguration0.getServlet());
      assertEquals("localhost", string0);
  }

  @Test
  public void test3()  throws Throwable  {
      HttpsConfiguration httpsConfiguration0 = new HttpsConfiguration();
      httpsConfiguration0.hasWebServerPort();
      assertEquals("/openjms-tunnel/tunnel", httpsConfiguration0.getServlet());
      assertEquals("localhost", httpsConfiguration0.getWebServerHost());
  }

  @Test
  public void test4()  throws Throwable  {
      HttpConfiguration httpConfiguration0 = new HttpConfiguration();
      int int0 = httpConfiguration0.getWebServerPort();
      assertEquals("/openjms-tunnel/tunnel", httpConfiguration0.getServlet());
      assertEquals("localhost", httpConfiguration0.getWebServerHost());
      assertEquals(0, int0);
  }
}
