/*
 * This file was automatically generated by EvoSuite
 */

package org.exolab.jms.config;

import org.junit.Test;
import org.junit.runner.RunWith;
import org.evosuite.junit.EvoSuiteRunner;
import static org.junit.Assert.*;
import org.exolab.jms.config.HttpConfiguration;
import org.exolab.jms.config.HttpsConfiguration;
import org.exolab.jms.config.TcpConfiguration;
import org.exolab.jms.config.TcpsConfiguration;
import org.junit.BeforeClass;

@RunWith(EvoSuiteRunner.class)
public class TestSocketConfigurationType {

  @BeforeClass 
  public static void initEvoSuiteFramework(){ 
    org.evosuite.Properties.REPLACE_CALLS = true; 
  } 


  @Test
  public void test0()  throws Throwable  {
      TcpsConfiguration tcpsConfiguration0 = new TcpsConfiguration();
      tcpsConfiguration0.deleteJndiPort();
      assertEquals(0, tcpsConfiguration0.getAdminPort());
      assertEquals(true, tcpsConfiguration0.getBindAll());
      assertEquals(0, tcpsConfiguration0.getJndiPort());
      assertEquals(false, tcpsConfiguration0.hasJndiPort());
  }

  @Test
  public void test1()  throws Throwable  {
      HttpConfiguration httpConfiguration0 = new HttpConfiguration();
      int int0 = httpConfiguration0.getPort();
      assertEquals(true, httpConfiguration0.getBindAll());
      assertEquals(0, httpConfiguration0.getAdminPort());
      assertEquals(0, int0);
      assertEquals(0, httpConfiguration0.getJndiPort());
  }

  @Test
  public void test2()  throws Throwable  {
      HttpConfiguration httpConfiguration0 = new HttpConfiguration();
      httpConfiguration0.setJndiPort(0);
      assertEquals(true, httpConfiguration0.hasJndiPort());
      assertEquals(0, httpConfiguration0.getAdminPort());
  }

  @Test
  public void test3()  throws Throwable  {
      TcpsConfiguration tcpsConfiguration0 = new TcpsConfiguration();
      tcpsConfiguration0.deleteAdminPort();
      assertEquals(true, tcpsConfiguration0.getBindAll());
      assertEquals(0, tcpsConfiguration0.getAdminPort());
      assertEquals(0, tcpsConfiguration0.getJndiPort());
      assertEquals(false, tcpsConfiguration0.hasAdminPort());
  }

  @Test
  public void test4()  throws Throwable  {
      TcpConfiguration tcpConfiguration0 = new TcpConfiguration();
      int int0 = tcpConfiguration0.getJndiPort();
      assertEquals(true, tcpConfiguration0.getBindAll());
      assertEquals(0, tcpConfiguration0.getAdminPort());
      assertEquals(0, int0);
  }

  @Test
  public void test5()  throws Throwable  {
      HttpsConfiguration httpsConfiguration0 = new HttpsConfiguration();
      httpsConfiguration0.hasAdminPort();
      assertEquals(true, httpsConfiguration0.getBindAll());
      assertEquals(0, httpsConfiguration0.getJndiPort());
      assertEquals(0, httpsConfiguration0.getAdminPort());
  }

  @Test
  public void test6()  throws Throwable  {
      HttpConfiguration httpConfiguration0 = new HttpConfiguration();
      httpConfiguration0.hasBindAll();
      assertEquals(true, httpConfiguration0.getBindAll());
      assertEquals(0, httpConfiguration0.getJndiPort());
      assertEquals(0, httpConfiguration0.getAdminPort());
  }

  @Test
  public void test7()  throws Throwable  {
      TcpConfiguration tcpConfiguration0 = new TcpConfiguration();
      tcpConfiguration0.hasJndiPort();
      assertEquals(true, tcpConfiguration0.getBindAll());
      assertEquals(0, tcpConfiguration0.getAdminPort());
      assertEquals(0, tcpConfiguration0.getJndiPort());
  }

  @Test
  public void test8()  throws Throwable  {
      TcpConfiguration tcpConfiguration0 = new TcpConfiguration();
      int int0 = tcpConfiguration0.getAdminPort();
      assertEquals(0, tcpConfiguration0.getJndiPort());
      assertEquals(0, int0);
      assertEquals(true, tcpConfiguration0.getBindAll());
  }

  @Test
  public void test9()  throws Throwable  {
      HttpsConfiguration httpsConfiguration0 = new HttpsConfiguration();
      httpsConfiguration0.setAdminPort((-94));
      assertEquals(-94, httpsConfiguration0.getAdminPort());
      assertEquals(true, httpsConfiguration0.hasAdminPort());
  }

  @Test
  public void test10()  throws Throwable  {
      TcpsConfiguration tcpsConfiguration0 = new TcpsConfiguration();
      tcpsConfiguration0.hasPort();
      assertEquals(true, tcpsConfiguration0.getBindAll());
      assertEquals(0, tcpsConfiguration0.getAdminPort());
      assertEquals(0, tcpsConfiguration0.getJndiPort());
  }

  @Test
  public void test11()  throws Throwable  {
      HttpConfiguration httpConfiguration0 = new HttpConfiguration();
      httpConfiguration0.setPort(177);
      assertEquals(177, httpConfiguration0.getPort());
      assertEquals(0, httpConfiguration0.getAdminPort());
  }

  @Test
  public void test12()  throws Throwable  {
      TcpConfiguration tcpConfiguration0 = new TcpConfiguration();
      boolean boolean0 = tcpConfiguration0.getBindAll();
      assertEquals(0, tcpConfiguration0.getJndiPort());
      assertEquals(0, tcpConfiguration0.getAdminPort());
      assertEquals(true, boolean0);
  }

  @Test
  public void test13()  throws Throwable  {
      HttpsConfiguration httpsConfiguration0 = new HttpsConfiguration();
      httpsConfiguration0.setBindAll(false);
      assertEquals(true, httpsConfiguration0.hasBindAll());
      assertEquals(false, httpsConfiguration0.getBindAll());
  }

  @Test
  public void test14()  throws Throwable  {
      TcpConfiguration tcpConfiguration0 = new TcpConfiguration();
      tcpConfiguration0.deleteBindAll();
      assertEquals(0, tcpConfiguration0.getJndiPort());
      assertEquals(false, tcpConfiguration0.hasBindAll());
      assertEquals(0, tcpConfiguration0.getAdminPort());
      assertEquals(true, tcpConfiguration0.getBindAll());
  }
}
