/*
 * This file was automatically generated by EvoSuite
 */

package org.exolab.jms.config;

import org.junit.Test;
import org.junit.runner.RunWith;
import org.evosuite.junit.EvoSuiteRunner;
import static org.junit.Assert.*;
import java.io.IOException;
import java.io.Reader;
import java.io.StringWriter;
import java.io.Writer;
import java.util.Enumeration;
import org.exolab.castor.xml.MarshalException;
import org.exolab.castor.xml.ValidationException;
import org.exolab.jms.config.AdministeredDestinations;
import org.exolab.jms.config.AdministeredQueue;
import org.exolab.jms.config.AdministeredTopic;
import org.junit.BeforeClass;
import org.xml.sax.ContentHandler;

@RunWith(EvoSuiteRunner.class)
public class TestAdministeredDestinations {

  @BeforeClass 
  public static void initEvoSuiteFramework(){ 
    org.evosuite.Properties.REPLACE_CALLS = true; 
  } 


  @Test
  public void test0()  throws Throwable  {
      AdministeredDestinations administeredDestinations0 = new AdministeredDestinations();
      AdministeredQueue administeredQueue0 = new AdministeredQueue();
      administeredDestinations0.addAdministeredQueue(0, administeredQueue0);
      assertEquals(1, administeredDestinations0.getAdministeredQueueCount());
      assertEquals(false, administeredDestinations0.isValid());
  }

  @Test
  public void test1()  throws Throwable  {
      AdministeredDestinations administeredDestinations0 = new AdministeredDestinations();
      AdministeredTopic administeredTopic0 = new AdministeredTopic();
      administeredDestinations0.addAdministeredTopic(0, administeredTopic0);
      assertEquals(1, administeredDestinations0.getAdministeredTopicCount());
      assertEquals(false, administeredDestinations0.isValid());
  }

  @Test
  public void test2()  throws Throwable  {
      AdministeredDestinations administeredDestinations0 = new AdministeredDestinations();
      administeredDestinations0.clearAdministeredQueue();
      assertEquals(true, administeredDestinations0.isValid());
  }

  @Test
  public void test3()  throws Throwable  {
      AdministeredDestinations administeredDestinations0 = new AdministeredDestinations();
      Enumeration<Object> enumeration0 = administeredDestinations0.enumerateAdministeredTopic();
      assertEquals(false, enumeration0.hasMoreElements());
  }

  @Test
  public void test4()  throws Throwable  {
      AdministeredDestinations administeredDestinations0 = new AdministeredDestinations();
      AdministeredQueue administeredQueue0 = new AdministeredQueue();
      administeredDestinations0.addAdministeredQueue(administeredQueue0);
      assertEquals(false, administeredDestinations0.isValid());
      assertEquals(1, administeredDestinations0.getAdministeredQueueCount());
  }

  @Test
  public void test5()  throws Throwable  {
      AdministeredDestinations administeredDestinations0 = new AdministeredDestinations();
      AdministeredTopic administeredTopic0 = new AdministeredTopic();
      boolean boolean0 = administeredDestinations0.removeAdministeredTopic(administeredTopic0);
      assertEquals(false, boolean0);
  }

  @Test
  public void test6()  throws Throwable  {
      AdministeredDestinations administeredDestinations0 = new AdministeredDestinations();
      Enumeration<Object> enumeration0 = administeredDestinations0.enumerateAdministeredQueue();
      assertEquals(false, enumeration0.hasMoreElements());
  }

  @Test
  public void test7()  throws Throwable  {
      AdministeredDestinations administeredDestinations0 = new AdministeredDestinations();
      AdministeredTopic administeredTopic0 = new AdministeredTopic();
      administeredDestinations0.addAdministeredTopic(administeredTopic0);
      StringWriter stringWriter0 = new StringWriter(0);
      try {
        administeredDestinations0.marshal((Writer) stringWriter0);
        fail("Expecting exception: ValidationException");
      } catch(ValidationException e) {
        /*
         * name is a required field.
         */
      }
  }

  @Test
  public void test8()  throws Throwable  {
      AdministeredDestinations administeredDestinations0 = new AdministeredDestinations();
      boolean boolean0 = administeredDestinations0.isValid();
      assertEquals(true, boolean0);
  }

  @Test
  public void test9()  throws Throwable  {
      AdministeredDestinations administeredDestinations0 = new AdministeredDestinations();
      int int0 = administeredDestinations0.getAdministeredTopicCount();
      assertEquals(0, int0);
  }

  @Test
  public void test10()  throws Throwable  {
      AdministeredDestinations administeredDestinations0 = new AdministeredDestinations();
      int int0 = administeredDestinations0.getAdministeredQueueCount();
      assertEquals(0, int0);
  }

  @Test
  public void test11()  throws Throwable  {
      AdministeredDestinations administeredDestinations0 = new AdministeredDestinations();
      // Undeclared exception!
      try {
        administeredDestinations0.marshal((ContentHandler) null);
        fail("Expecting exception: IllegalArgumentException");
      } catch(IllegalArgumentException e) {
        /*
         * Argument 'handler' is null.
         */
      }
  }

  @Test
  public void test12()  throws Throwable  {
      AdministeredDestinations administeredDestinations0 = new AdministeredDestinations();
      StringWriter stringWriter0 = new StringWriter(0);
      administeredDestinations0.marshal((Writer) stringWriter0);
      assertEquals("<?xml version=\"1.0\" encoding=\"UTF-8\"?>\n<AdministeredDestinations xmlns=\"http://openjms.exolab.org/configuration\"/>", stringWriter0.toString());
  }

  @Test
  public void test13()  throws Throwable  {
      AdministeredDestinations administeredDestinations0 = new AdministeredDestinations();
      administeredDestinations0.clearAdministeredTopic();
      assertEquals(0, administeredDestinations0.getAdministeredTopicCount());
  }

  @Test
  public void test14()  throws Throwable  {
      AdministeredDestinations administeredDestinations0 = new AdministeredDestinations();
      boolean boolean0 = administeredDestinations0.removeAdministeredQueue((AdministeredQueue) null);
      assertEquals(false, boolean0);
  }

  @Test
  public void test15()  throws Throwable  {
      AdministeredDestinations administeredDestinations0 = new AdministeredDestinations();
      try {
        administeredDestinations0.getAdministeredQueue((-1));
        fail("Expecting exception: IndexOutOfBoundsException");
      } catch(IndexOutOfBoundsException e) {
      }
  }

  @Test
  public void test16()  throws Throwable  {
      AdministeredDestinations administeredDestinations0 = new AdministeredDestinations();
      try {
        administeredDestinations0.getAdministeredQueue(0);
        fail("Expecting exception: IndexOutOfBoundsException");
      } catch(IndexOutOfBoundsException e) {
        /*
         * Index: 0, Size: 0
         */
      }
  }

  @Test
  public void test17()  throws Throwable  {
      AdministeredDestinations administeredDestinations0 = new AdministeredDestinations();
      try {
        administeredDestinations0.getAdministeredQueue(57343);
        fail("Expecting exception: IndexOutOfBoundsException");
      } catch(IndexOutOfBoundsException e) {
      }
  }

  @Test
  public void test18()  throws Throwable  {
      AdministeredDestinations administeredDestinations0 = new AdministeredDestinations();
      AdministeredQueue[] administeredQueueArray0 = new AdministeredQueue[1];
      administeredDestinations0.setAdministeredQueue(administeredQueueArray0);
      administeredDestinations0.getAdministeredQueue();
      assertEquals(1, administeredDestinations0.getAdministeredQueueCount());
      assertEquals(false, administeredDestinations0.isValid());
  }

  @Test
  public void test19()  throws Throwable  {
      AdministeredDestinations administeredDestinations0 = new AdministeredDestinations();
      try {
        administeredDestinations0.getAdministeredTopic((-826));
        fail("Expecting exception: IndexOutOfBoundsException");
      } catch(IndexOutOfBoundsException e) {
      }
  }

  @Test
  public void test20()  throws Throwable  {
      AdministeredDestinations administeredDestinations0 = new AdministeredDestinations();
      try {
        administeredDestinations0.getAdministeredTopic(0);
        fail("Expecting exception: IndexOutOfBoundsException");
      } catch(IndexOutOfBoundsException e) {
        /*
         * Index: 0, Size: 0
         */
      }
  }

  @Test
  public void test21()  throws Throwable  {
      AdministeredDestinations administeredDestinations0 = new AdministeredDestinations();
      try {
        administeredDestinations0.getAdministeredTopic(1);
        fail("Expecting exception: IndexOutOfBoundsException");
      } catch(IndexOutOfBoundsException e) {
      }
  }

  @Test
  public void test22()  throws Throwable  {
      AdministeredDestinations administeredDestinations0 = new AdministeredDestinations();
      AdministeredQueue[] administeredQueueArray0 = new AdministeredQueue[1];
      try {
        administeredDestinations0.setAdministeredQueue(1, administeredQueueArray0[0]);
        fail("Expecting exception: IndexOutOfBoundsException");
      } catch(IndexOutOfBoundsException e) {
      }
  }

  @Test
  public void test23()  throws Throwable  {
      AdministeredDestinations administeredDestinations0 = new AdministeredDestinations();
      AdministeredQueue[] administeredQueueArray0 = new AdministeredQueue[1];
      AdministeredQueue administeredQueue0 = new AdministeredQueue();
      administeredDestinations0.setAdministeredQueue(administeredQueueArray0);
      try {
        administeredDestinations0.setAdministeredQueue(1, administeredQueue0);
        fail("Expecting exception: IndexOutOfBoundsException");
      } catch(IndexOutOfBoundsException e) {
        /*
         * Index: 1, Size: 1
         */
      }
  }

  @Test
  public void test24()  throws Throwable  {
      AdministeredDestinations administeredDestinations0 = new AdministeredDestinations();
      try {
        administeredDestinations0.setAdministeredTopic(0, (AdministeredTopic) null);
        fail("Expecting exception: IndexOutOfBoundsException");
      } catch(IndexOutOfBoundsException e) {
        /*
         * Index: 0, Size: 0
         */
      }
  }

  @Test
  public void test25()  throws Throwable  {
      AdministeredDestinations administeredDestinations0 = new AdministeredDestinations();
      AdministeredTopic administeredTopic0 = new AdministeredTopic();
      try {
        administeredDestinations0.setAdministeredTopic(3673, administeredTopic0);
        fail("Expecting exception: IndexOutOfBoundsException");
      } catch(IndexOutOfBoundsException e) {
      }
  }

  @Test
  public void test26()  throws Throwable  {
      AdministeredDestinations administeredDestinations0 = new AdministeredDestinations();
      AdministeredTopic[] administeredTopicArray0 = new AdministeredTopic[4];
      administeredDestinations0.setAdministeredTopic(administeredTopicArray0);
      assertEquals(false, administeredDestinations0.isValid());
      assertEquals(4, administeredDestinations0.getAdministeredTopicCount());
  }

  @Test
  public void test27()  throws Throwable  {
      try {
        AdministeredDestinations.unmarshal((Reader) null);
        fail("Expecting exception: MarshalException");
      } catch(MarshalException e) {
        /*
         * 
         */
      }
  }
}
