/*
 * This file was automatically generated by EvoSuite
 */

package org.exolab.jms.config;

import org.junit.Test;
import org.junit.runner.RunWith;
import org.evosuite.junit.EvoSuiteRunner;
import static org.junit.Assert.*;
import org.exolab.castor.mapping.ClassDescriptor;
import org.exolab.castor.mapping.MappingException;
import org.exolab.castor.xml.util.XMLClassDescriptorAdapter;
import org.exolab.jms.config.TcpConfigurationDescriptor;
import org.junit.BeforeClass;

@RunWith(EvoSuiteRunner.class)
public class TestTcpConfigurationDescriptor {

  @BeforeClass 
  public static void initEvoSuiteFramework(){ 
    org.evosuite.Properties.REPLACE_CALLS = true; 
  } 


  @Test
  public void test0()  throws Throwable  {
      TcpConfigurationDescriptor tcpConfigurationDescriptor0 = new TcpConfigurationDescriptor();
      String string0 = tcpConfigurationDescriptor0.getNameSpaceURI();
      assertEquals("http://openjms.exolab.org/configuration", string0);
      assertEquals("TcpConfiguration", tcpConfigurationDescriptor0.getXMLName());
      assertNotNull(string0);
  }

  @Test
  public void test1()  throws Throwable  {
      TcpConfigurationDescriptor tcpConfigurationDescriptor0 = new TcpConfigurationDescriptor();
      XMLClassDescriptorAdapter xMLClassDescriptorAdapter0 = new XMLClassDescriptorAdapter((ClassDescriptor) tcpConfigurationDescriptor0, (String) null);
      assertEquals("TcpConfiguration", xMLClassDescriptorAdapter0.getXMLName());
      assertEquals("http://openjms.exolab.org/configuration", tcpConfigurationDescriptor0.getNameSpaceURI());
  }

  @Test
  public void test2()  throws Throwable  {
      TcpConfigurationDescriptor tcpConfigurationDescriptor0 = new TcpConfigurationDescriptor();
      TcpConfigurationDescriptor tcpConfigurationDescriptor1 = (TcpConfigurationDescriptor)tcpConfigurationDescriptor0.getValidator();
      assertEquals("TcpConfiguration", tcpConfigurationDescriptor0.getXMLName());
      assertEquals("http://openjms.exolab.org/configuration", tcpConfigurationDescriptor0.getNameSpaceURI());
      assertEquals("TcpConfiguration", tcpConfigurationDescriptor1.getXMLName());
  }

  @Test
  public void test3()  throws Throwable  {
      TcpConfigurationDescriptor tcpConfigurationDescriptor0 = new TcpConfigurationDescriptor();
      tcpConfigurationDescriptor0.getNameSpacePrefix();
      assertEquals("TcpConfiguration", tcpConfigurationDescriptor0.getXMLName());
      assertEquals("http://openjms.exolab.org/configuration", tcpConfigurationDescriptor0.getNameSpaceURI());
  }

  @Test
  public void test4()  throws Throwable  {
      TcpConfigurationDescriptor tcpConfigurationDescriptor0 = new TcpConfigurationDescriptor();
      tcpConfigurationDescriptor0.getAccessMode();
      assertEquals("http://openjms.exolab.org/configuration", tcpConfigurationDescriptor0.getNameSpaceURI());
      assertEquals("TcpConfiguration", tcpConfigurationDescriptor0.getXMLName());
  }
}
