/*
 * This file was automatically generated by EvoSuite
 */

package org.exolab.jms.config;

import org.junit.Test;
import org.junit.runner.RunWith;
import org.evosuite.junit.EvoSuiteRunner;
import static org.junit.Assert.*;
import java.io.CharArrayWriter;
import java.io.IOException;
import java.io.PipedReader;
import java.io.Reader;
import java.io.Writer;
import org.exolab.castor.util.NestedIOException;
import org.exolab.castor.xml.MarshalException;
import org.exolab.castor.xml.ValidationException;
import org.exolab.jms.config.Server;
import org.exolab.jms.config.types.SchemeType;
import org.junit.BeforeClass;
import org.xml.sax.ContentHandler;
import org.xml.sax.SAXException;
import org.xml.sax.helpers.XMLReaderAdapter;

@RunWith(EvoSuiteRunner.class)
public class TestServer {

  @BeforeClass 
  public static void initEvoSuiteFramework(){ 
    org.evosuite.Properties.REPLACE_CALLS = true; 
  } 


  @Test
  public void test0()  throws Throwable  {
      Server server0 = new Server();
      CharArrayWriter charArrayWriter0 = new CharArrayWriter();
      try {
        server0.marshal((Writer) charArrayWriter0);
        fail("Expecting exception: ValidationException");
      } catch(ValidationException e) {
        /*
         * proxy-class is a required field.
         */
      }
  }

  @Test
  public void test1()  throws Throwable  {
      Server server0 = new Server();
      boolean boolean0 = server0.isValid();
      assertEquals(false, boolean0);
  }

  @Test
  public void test2()  throws Throwable  {
      Server server0 = new Server();
      String string0 = server0.getImplementationClass();
      assertNull(string0);
  }

  @Test
  public void test3()  throws Throwable  {
      Server server0 = new Server();
      XMLReaderAdapter xMLReaderAdapter0 = new XMLReaderAdapter();
      try {
        server0.marshal((ContentHandler) xMLReaderAdapter0);
        fail("Expecting exception: NestedIOException");
      } catch(NestedIOException e) {
        /*
         * System property org.xml.sax.parser not specified
         */
      }
  }

  @Test
  public void test4()  throws Throwable  {
      Server server0 = new Server();
      SchemeType schemeType0 = SchemeType.HTTPS;
      server0.setScheme(schemeType0);
      assertEquals(3, schemeType0.getType());
  }

  @Test
  public void test5()  throws Throwable  {
      Server server0 = new Server();
      server0.setProxyClass("-YR1");
      assertEquals("-YR1", server0.getProxyClass());
  }

  @Test
  public void test6()  throws Throwable  {
      Server server0 = new Server();
      server0.setImplementationClass("-YR1");
      assertEquals(false, server0.isValid());
  }

  @Test
  public void test7()  throws Throwable  {
      Server server0 = new Server();
      SchemeType schemeType0 = server0.getScheme();
      assertNull(schemeType0);
  }

  @Test
  public void test8()  throws Throwable  {
      PipedReader pipedReader0 = new PipedReader();
      try {
        Server.unmarshal((Reader) pipedReader0);
        fail("Expecting exception: MarshalException");
      } catch(MarshalException e) {
        /*
         * Pipe not connected
         */
      }
  }
}
