/*
 * This file was automatically generated by EvoSuite
 */

package org.exolab.jms.persistence;

import org.junit.Test;
import org.junit.runner.RunWith;
import org.evosuite.junit.EvoSuiteRunner;
import static org.junit.Assert.*;
import org.exolab.jms.config.DatabaseConfiguration;
import org.exolab.jms.config.RdbmsDatabaseConfiguration;
import org.exolab.jms.persistence.PersistenceException;
import org.exolab.jms.persistence.RDBMSAdapter;
import org.junit.BeforeClass;

@RunWith(EvoSuiteRunner.class)
public class TestRDBMSAdapter {

  @BeforeClass 
  public static void initEvoSuiteFramework(){ 
    org.evosuite.Properties.REPLACE_CALLS = true; 
  } 


  @Test
  public void test0()  throws Throwable  {
      DatabaseConfiguration databaseConfiguration0 = new DatabaseConfiguration();
      RdbmsDatabaseConfiguration rdbmsDatabaseConfiguration0 = new RdbmsDatabaseConfiguration();
      databaseConfiguration0.setRdbmsDatabaseConfiguration(rdbmsDatabaseConfiguration0);
      RDBMSAdapter rDBMSAdapter0 = null;
      try {
        rDBMSAdapter0 = new RDBMSAdapter(databaseConfiguration0, "org.apache.derby.iapi.sql.execute.ExecRow", "org.apache.derby.iapi.sql.execute.ExecRow", "org.apache.derby.iapi.sql.execute.ExecRow", "org.apache.derby.iapi.sql.execute.ExecRow");
        fail("Expecting exception: PersistenceException");
      } catch(PersistenceException e) {
        /*
         * Failed to get pooled connection
         */
      }
  }
}
