/*
 * This file was automatically generated by EvoSuite
 */

package org.exolab.jms.client;

import org.junit.Test;
import org.junit.runner.RunWith;
import org.evosuite.junit.EvoSuiteRunner;
import static org.junit.Assert.*;
import java.util.Hashtable;
import java.util.Properties;
import javax.naming.Context;
import javax.naming.InitialContext;
import javax.naming.Name;
import javax.naming.NamingException;
import javax.naming.Reference;
import org.exolab.jms.client.JmsConnectionFactoryBuilder;
import org.junit.BeforeClass;

@RunWith(EvoSuiteRunner.class)
public class TestJmsConnectionFactoryBuilder {

  @BeforeClass 
  public static void initEvoSuiteFramework(){ 
    org.evosuite.Properties.REPLACE_CALLS = true; 
  } 


  @Test
  public void test0()  throws Throwable  {
      JmsConnectionFactoryBuilder jmsConnectionFactoryBuilder0 = new JmsConnectionFactoryBuilder();
      InitialContext initialContext0 = new InitialContext();
      Hashtable<Reference, Reference> hashtable0 = new Hashtable<Reference, Reference>();
      Object object0 = jmsConnectionFactoryBuilder0.getObjectInstance((Object) "org.exolab.jms.client.JmsXAConnectionFactory", (Name) null, (Context) initialContext0, (Hashtable) hashtable0);
      assertNull(object0);
  }

  @Test
  public void test1()  throws Throwable  {
      JmsConnectionFactoryBuilder jmsConnectionFactoryBuilder0 = new JmsConnectionFactoryBuilder();
      InitialContext initialContext0 = new InitialContext();
      Hashtable<Reference, Reference> hashtable0 = new Hashtable<Reference, Reference>();
      Reference reference0 = new Reference("org.exolab.jms.client.JmsXAConnectionFactory");
      try {
        jmsConnectionFactoryBuilder0.getObjectInstance((Object) reference0, (Name) null, (Context) initialContext0, (Hashtable) hashtable0);
        fail("Expecting exception: NullPointerException");
      } catch(NullPointerException e) {
      }
  }

  @Test
  public void test2()  throws Throwable  {
      JmsConnectionFactoryBuilder jmsConnectionFactoryBuilder0 = new JmsConnectionFactoryBuilder();
      Properties properties0 = new Properties();
      Reference reference0 = new Reference("\u4E2D\u6587", "\u4E2D\u6587", "\u4E2D\u6587");
      InitialContext initialContext0 = new InitialContext();
      Object object0 = jmsConnectionFactoryBuilder0.getObjectInstance((Object) reference0, (Name) null, (Context) initialContext0, (Hashtable) properties0);
      assertNull(object0);
  }
}
