/*
 * This file was automatically generated by EvoSuite
 */

package org.exolab.jms.tools.admin;

import org.junit.Test;
import org.junit.runner.RunWith;
import org.evosuite.junit.EvoSuiteRunner;
import static org.junit.Assert.*;
import javax.swing.JTree;
import org.exolab.jms.tools.admin.OpenJMSTopic;
import org.junit.BeforeClass;

@RunWith(EvoSuiteRunner.class)
public class TestOpenJMSTopic {

  @BeforeClass 
  public static void initEvoSuiteFramework(){ 
    org.evosuite.Properties.REPLACE_CALLS = true; 
  } 


  @Test
  public void test0()  throws Throwable  {
      OpenJMSTopic openJMSTopic0 = new OpenJMSTopic("FgY${KgSFi", (JTree) null);
      // Undeclared exception!
      try {
        openJMSTopic0.update();
        fail("Expecting exception: NullPointerException");
      } catch(NullPointerException e) {
      }
  }
}
