/*
 * This file was automatically generated by EvoSuite
 */

package org.exolab.jms.tools.admin;

import org.junit.Test;
import org.junit.runner.RunWith;
import org.evosuite.junit.EvoSuiteRunner;
import static org.junit.Assert.*;
import java.awt.Rectangle;
import javax.swing.DefaultListCellRenderer;
import javax.swing.JTree;
import javax.swing.tree.TreeModel;
import org.exolab.jms.tools.admin.OpenJMSQueueFolder;
import org.junit.BeforeClass;

@RunWith(EvoSuiteRunner.class)
public class TestOpenJMSQueueFolder {

  @BeforeClass 
  public static void initEvoSuiteFramework(){ 
    org.evosuite.Properties.REPLACE_CALLS = true; 
  } 


  @Test
  public void test0()  throws Throwable  {
      OpenJMSQueueFolder openJMSQueueFolder0 = new OpenJMSQueueFolder((JTree) null);
      boolean boolean0 = openJMSQueueFolder0.getAllowsChildren();
      assertEquals(true, boolean0);
  }

  @Test
  public void test1()  throws Throwable  {
      JTree jTree0 = new JTree((TreeModel) null);
      OpenJMSQueueFolder openJMSQueueFolder0 = new OpenJMSQueueFolder(jTree0);
      openJMSQueueFolder0.createCommands();
      assertEquals(0, openJMSQueueFolder0.getDepth());
  }

  @Test
  public void test2()  throws Throwable  {
      JTree jTree0 = new JTree((TreeModel) null);
      OpenJMSQueueFolder openJMSQueueFolder0 = new OpenJMSQueueFolder(jTree0);
      String string0 = openJMSQueueFolder0.toString();
      assertEquals("Queues", string0);
  }

  @Test
  public void test3()  throws Throwable  {
      JTree jTree0 = new JTree((TreeModel) null);
      OpenJMSQueueFolder openJMSQueueFolder0 = new OpenJMSQueueFolder(jTree0);
      DefaultListCellRenderer defaultListCellRenderer0 = new DefaultListCellRenderer();
      Rectangle rectangle0 = defaultListCellRenderer0.getVisibleRect();
      openJMSQueueFolder0.displayCommands(rectangle0);
  }

  @Test
  public void test4()  throws Throwable  {
      JTree jTree0 = new JTree((TreeModel) null);
      OpenJMSQueueFolder openJMSQueueFolder0 = new OpenJMSQueueFolder(jTree0);
      boolean boolean0 = openJMSQueueFolder0.isLeaf();
      assertEquals(false, boolean0);
  }

  @Test
  public void test5()  throws Throwable  {
      OpenJMSQueueFolder openJMSQueueFolder0 = new OpenJMSQueueFolder((JTree) null);
      openJMSQueueFolder0.update();
      assertEquals(1, openJMSQueueFolder0.getSiblingCount());
  }
}
