/*
 * This file was automatically generated by EvoSuite
 */

package org.exolab.jms.tools.admin;

import org.junit.Test;
import org.junit.runner.RunWith;
import org.evosuite.junit.EvoSuiteRunner;
import static org.junit.Assert.*;
import java.awt.Rectangle;
import javax.swing.JTree;
import javax.swing.tree.TreeModel;
import org.exolab.jms.tools.admin.OpenJMSConsumer;
import org.junit.BeforeClass;

@RunWith(EvoSuiteRunner.class)
public class TestOpenJMSConsumer {

  @BeforeClass 
  public static void initEvoSuiteFramework(){ 
    org.evosuite.Properties.REPLACE_CALLS = true; 
  } 


  @Test
  public void test0()  throws Throwable  {
      OpenJMSConsumer openJMSConsumer0 = new OpenJMSConsumer("_EgL|PeIt^", (JTree) null);
      OpenJMSConsumer openJMSConsumer1 = (OpenJMSConsumer)openJMSConsumer0.getFirstLeaf();
      assertNotNull(openJMSConsumer1);
      assertEquals(true, openJMSConsumer0.isLeaf());
  }

  @Test
  public void test1()  throws Throwable  {
      JTree jTree0 = new JTree((TreeModel) null);
      OpenJMSConsumer openJMSConsumer0 = new OpenJMSConsumer("", jTree0);
      // Undeclared exception!
      try {
        openJMSConsumer0.displayCommands((Rectangle) null);
        fail("Expecting exception: NullPointerException");
      } catch(NullPointerException e) {
      }
  }

  @Test
  public void test2()  throws Throwable  {
      OpenJMSConsumer openJMSConsumer0 = new OpenJMSConsumer("_EgL|PeIt^", (JTree) null);
      openJMSConsumer0.createCommands();
      assertEquals("_EgL|PeIt^", openJMSConsumer0.toString());
  }

  @Test
  public void test3()  throws Throwable  {
      OpenJMSConsumer openJMSConsumer0 = new OpenJMSConsumer(";#p ${M=,", (JTree) null);
      String string0 = openJMSConsumer0.toString();
      assertEquals(";#p ${M=,", string0);
  }

  @Test
  public void test4()  throws Throwable  {
      OpenJMSConsumer openJMSConsumer0 = new OpenJMSConsumer(";#p ${M=,", (JTree) null);
      boolean boolean0 = openJMSConsumer0.getAllowsChildren();
      assertEquals(false, boolean0);
  }

  @Test
  public void test5()  throws Throwable  {
      OpenJMSConsumer openJMSConsumer0 = new OpenJMSConsumer(";#p ${M=,", (JTree) null);
      openJMSConsumer0.update();
      assertEquals(1, openJMSConsumer0.getSiblingCount());
  }
}
