/*
 * This file was automatically generated by EvoSuite
 */

package org.exolab.jms.tools.admin;

import org.junit.Test;
import org.junit.runner.RunWith;
import org.evosuite.junit.EvoSuiteRunner;
import static org.junit.Assert.*;
import javax.swing.JFrame;
import org.exolab.jms.tools.admin.QueryDialog;
import org.junit.BeforeClass;

@RunWith(EvoSuiteRunner.class)
public class TestQueryDialog {

  @BeforeClass 
  public static void initEvoSuiteFramework(){ 
    org.evosuite.Properties.REPLACE_CALLS = true; 
  } 


  @Test
  public void test0()  throws Throwable  {
      QueryDialog queryDialog0 = QueryDialog.instance();
      // Undeclared exception!
      try {
        queryDialog0.display((String) null);
        fail("Expecting exception: NoClassDefFoundError");
      } catch(NoClassDefFoundError e) {
        /*
         * Could not initialize class sun.font.FontScaler
         */
      }
  }

  @Test
  public void test1()  throws Throwable  {
      QueryDialog queryDialog0 = QueryDialog.create((JFrame) null);
      assertEquals(true, queryDialog0.isConfirmed());
  }

  @Test
  public void test2()  throws Throwable  {
      QueryDialog queryDialog0 = QueryDialog.instance();
      assertNotNull(queryDialog0);
      
      boolean boolean0 = queryDialog0.isConfirmed();
      assertEquals(true, boolean0);
  }
}
