/*
 * This file was automatically generated by EvoSuite
 */

package org.exolab.jms.tools.admin;

import org.junit.Test;
import org.junit.runner.RunWith;
import org.evosuite.junit.EvoSuiteRunner;
import static org.junit.Assert.*;
import java.awt.IllegalComponentStateException;
import java.awt.Rectangle;
import javax.swing.JTextPane;
import javax.swing.JTree;
import javax.swing.tree.DefaultTreeModel;
import javax.swing.tree.TreeModel;
import org.exolab.jms.tools.admin.OpenJMSServer;
import org.junit.BeforeClass;

@RunWith(EvoSuiteRunner.class)
public class TestOpenJMSServer {

  @BeforeClass 
  public static void initEvoSuiteFramework(){ 
    org.evosuite.Properties.REPLACE_CALLS = true; 
  } 


  @Test
  public void test0()  throws Throwable  {
      OpenJMSServer openJMSServer0 = new OpenJMSServer("", (JTree) null);
      openJMSServer0.createCommands();
      assertEquals("", openJMSServer0.toString());
  }

  @Test
  public void test1()  throws Throwable  {
      OpenJMSServer openJMSServer0 = new OpenJMSServer("B1,$:z5 c", (JTree) null);
      JTextPane jTextPane0 = new JTextPane();
      Rectangle rectangle0 = jTextPane0.getVisibleRect();
      // Undeclared exception!
      try {
        openJMSServer0.displayCommands(rectangle0);
        fail("Expecting exception: IllegalComponentStateException");
      } catch(IllegalComponentStateException e) {
        /*
         * component must be showing on the screen to determine its location
         */
      }
      assertEquals(0, openJMSServer0.getLevel());
  }

  @Test
  public void test2()  throws Throwable  {
      OpenJMSServer openJMSServer0 = new OpenJMSServer("", (JTree) null);
      String string0 = openJMSServer0.toString();
      assertEquals("", string0);
  }

  @Test
  public void test3()  throws Throwable  {
      OpenJMSServer openJMSServer0 = new OpenJMSServer("", (JTree) null);
      boolean boolean0 = openJMSServer0.getAllowsChildren();
      assertEquals(true, boolean0);
  }

  @Test
  public void test4()  throws Throwable  {
      DefaultTreeModel defaultTreeModel0 = OpenJMSServer.createServerList((JTree) null);
      assertEquals(false, defaultTreeModel0.asksAllowsChildren());
  }

  @Test
  public void test5()  throws Throwable  {
      JTree jTree0 = new JTree((TreeModel) null);
      OpenJMSServer openJMSServer0 = new OpenJMSServer("", jTree0);
      // Undeclared exception!
      try {
        openJMSServer0.refresh();
        fail("Expecting exception: NullPointerException");
      } catch(NullPointerException e) {
      }
  }
}
