/*
 * This file was automatically generated by EvoSuite
 */

package org.exolab.jms.tools.admin;

import org.junit.Test;
import org.junit.runner.RunWith;
import org.evosuite.junit.EvoSuiteRunner;
import static org.junit.Assert.*;
import java.awt.IllegalComponentStateException;
import java.awt.Rectangle;
import javax.swing.DefaultListCellRenderer;
import javax.swing.JTree;
import javax.swing.tree.TreeModel;
import org.exolab.jms.tools.admin.OpenJMSConsumerFolder;
import org.junit.BeforeClass;

@RunWith(EvoSuiteRunner.class)
public class TestOpenJMSConsumerFolder {

  @BeforeClass 
  public static void initEvoSuiteFramework(){ 
    org.evosuite.Properties.REPLACE_CALLS = true; 
  } 


  @Test
  public void test0()  throws Throwable  {
      JTree jTree0 = new JTree((TreeModel) null);
      OpenJMSConsumerFolder openJMSConsumerFolder0 = new OpenJMSConsumerFolder(jTree0);
      boolean boolean0 = openJMSConsumerFolder0.isLeaf();
      assertEquals(false, boolean0);
  }

  @Test
  public void test1()  throws Throwable  {
      JTree jTree0 = new JTree((TreeModel) null);
      OpenJMSConsumerFolder openJMSConsumerFolder0 = new OpenJMSConsumerFolder(jTree0);
      String string0 = openJMSConsumerFolder0.toString();
      assertEquals("Consumers", string0);
  }

  @Test
  public void test2()  throws Throwable  {
      JTree jTree0 = new JTree((TreeModel) null);
      OpenJMSConsumerFolder openJMSConsumerFolder0 = new OpenJMSConsumerFolder(jTree0);
      DefaultListCellRenderer defaultListCellRenderer0 = new DefaultListCellRenderer();
      Rectangle rectangle0 = defaultListCellRenderer0.getVisibleRect();
      // Undeclared exception!
      try {
        openJMSConsumerFolder0.displayCommands(rectangle0);
        fail("Expecting exception: IllegalComponentStateException");
      } catch(IllegalComponentStateException e) {
        /*
         * component must be showing on the screen to determine its location
         */
      }
  }

  @Test
  public void test3()  throws Throwable  {
      OpenJMSConsumerFolder openJMSConsumerFolder0 = new OpenJMSConsumerFolder((JTree) null);
      openJMSConsumerFolder0.update();
      assertEquals(true, openJMSConsumerFolder0.getAllowsChildren());
  }

  @Test
  public void test4()  throws Throwable  {
      OpenJMSConsumerFolder openJMSConsumerFolder0 = new OpenJMSConsumerFolder((JTree) null);
      boolean boolean0 = openJMSConsumerFolder0.getAllowsChildren();
      assertEquals(true, boolean0);
  }

  @Test
  public void test5()  throws Throwable  {
      JTree jTree0 = new JTree((TreeModel) null);
      OpenJMSConsumerFolder openJMSConsumerFolder0 = new OpenJMSConsumerFolder(jTree0);
      openJMSConsumerFolder0.createCommands();
      assertEquals(true, openJMSConsumerFolder0.isRoot());
  }
}
