/*
 * This file was automatically generated by EvoSuite
 */

package org.exolab.jms.tools.admin;

import org.junit.Test;
import org.junit.runner.RunWith;
import org.evosuite.junit.EvoSuiteRunner;
import static org.junit.Assert.*;
import javax.swing.JTree;
import org.exolab.jms.tools.admin.OpenJMSQueue;
import org.junit.BeforeClass;

@RunWith(EvoSuiteRunner.class)
public class TestOpenJMSQueue {

  @BeforeClass 
  public static void initEvoSuiteFramework(){ 
    org.evosuite.Properties.REPLACE_CALLS = true; 
  } 


  @Test
  public void test0()  throws Throwable  {
      OpenJMSQueue openJMSQueue0 = new OpenJMSQueue("_ATD$gw;B\"tc7", (JTree) null);
      openJMSQueue0.update();
      assertEquals(false, openJMSQueue0.isLeaf());
  }
}
