/*
 * This file was automatically generated by EvoSuite
 */

package org.exolab.jms.tools.admin;

import org.junit.Test;
import org.junit.runner.RunWith;
import org.evosuite.junit.EvoSuiteRunner;
import static org.junit.Assert.*;
import org.exolab.jms.tools.admin.AdminInfo;
import org.junit.BeforeClass;

@RunWith(EvoSuiteRunner.class)
public class TestAdminInfo {

  @BeforeClass 
  public static void initEvoSuiteFramework(){ 
    org.evosuite.Properties.REPLACE_CALLS = true; 
  } 


  @Test
  public void test0()  throws Throwable  {
      AdminInfo adminInfo0 = null;
      try {
        adminInfo0 = new AdminInfo();
        fail("Expecting exception: NoClassDefFoundError");
      } catch(NoClassDefFoundError e) {
        /*
         * Could not initialize class sun.font.FontScaler
         */
      }
  }
}
