/*
 * This file was automatically generated by EvoSuite
 */

package org.exolab.jms.server;

import org.junit.Test;
import org.junit.runner.RunWith;
import org.evosuite.junit.EvoSuiteRunner;
import static org.junit.Assert.*;
import org.exolab.jms.config.Configuration;
import org.exolab.jms.server.EmbeddedJmsServer;
import org.exolab.jms.server.ServerException;
import org.junit.BeforeClass;

@RunWith(EvoSuiteRunner.class)
public class TestEmbeddedJmsServer {

  @BeforeClass 
  public static void initEvoSuiteFramework(){ 
    org.evosuite.Properties.REPLACE_CALLS = true; 
  } 


  @Test
  public void test0()  throws Throwable  {
      Configuration configuration0 = new Configuration();
      EmbeddedJmsServer embeddedJmsServer0 = new EmbeddedJmsServer(configuration0);
      embeddedJmsServer0.run();
  }
}
